// 《职场营销博弈》372 张内容源（真实职场案例）。
// 由 tools/gen_campaign.js 读取并归一化、写入 design/cards/campaign.json 与 web/cards.js / docs/cards.js。
//
// 结构：
//   MAJORS：60 张大事件。每张含 4 张小事件（minors，具体子案例）+ 4 个主选项（choices）。
//   RANDOMS：72 张随机事件（独立微事件）。
// 选项字段：
//   id      选项内部 id（全局唯一）
//   label   选项按钮文案（真实、口语、有张力）
//   arch    行为原型（影响数值与 AI 效用，沿用引擎 arch 词表）
//   lean    该选项主要效力的派系（null 表示不偏袒），用于 faction_trust 正负分配
//   side    "left"（稳妥）或 "right"（进取），决定 reigns 二选一的左右
//
// 注意：数值（player / faction_trust）由 gen_campaign.js 按 arch+side+lean 确定性生成，
//       本文件只负责「真实职场案例」的可见文案与选项意图，避免手写 1488 条数值。

const MAJORS = [
  // ============ 第一卷：2026.7–2027.6 入职与生存期 ============
  {
    id: "M01", cat: "入职", title: "第一周的入职培训",
    text: "HR 把一摞塑封手册拍在你桌上：工牌、保密协议、报销流程。讲师念到「末位淘汰」时，全屋静了一秒。",
    flavor: "手册越厚，套得越紧。",
    minors: [
      { title: "培训被点名复盘", text: "分组演练时讲师突然点你名，要你当众复述本组方案。四十双眼睛转过来。", flavor: "第一次被看见，未必是好事。" },
      { title: "工牌权限的微妙", text: "你的门禁只能进本层，隔壁组的实习生却能刷开机房。权限表上早分了三六九等。", flavor: "门禁卡比工牌更早告诉你位置。" },
      { title: "导师的「过来人」忠告", text: "分配给你的导师泡了杯茶，说「别学上一届那个刺头，听话的人走得远」。", flavor: "他嘴里的刺头，现在在竞品那头。" },
      { title: "晚上十点的钉钉", text: "入职第三天，群里 22:47 弹出一条「收到请回复」。你盯着屏幕，回了「收到」。", flavor: "第一条收到的，是你没有下班权的证据。" },
    ],
    choices: [
      { id: "M01c1", label: "老实记下每一条规矩", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M01c2", label: "主动加讲师微信请教", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M01c3", label: "私下打探「末位淘汰」实情", arch: "dodge", lean: "FV_A", side: "right" },
      { id: "M01c4", label: "复盘时抢答露一手", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M02", cat: "站队", title: "领导饭局上的递话",
    text: "部门总请新人在小馆子吃饭，酒过三巡忽然说：「以后有想法，直接找我，别绕弯子。」桌下却有人踢了你一脚。",
    flavor: "话是递给你，坑也是递给你。",
    minors: [
      { title: "谁坐了你旁边", text: "落座时行政总监把你安排在总助左侧——那是「自己人」的默认位。", flavor: "座位表比组织架构图诚实。" },
      { title: "敬酒的先后顺序", text: "有人教你先敬大领导再敬直属，有人笑你「太不懂事」。规矩不止一套。", flavor: "酒杯举错方向，比说错话更得罪人。" },
      { title: "领导那句「自己人」", text: "散场时总搂你肩说「好好干，我看好你」。你分不清是鸡汤还是饵。", flavor: "被看好的代价，是更显眼的目标。" },
      { title: "饭后的小群邀请", text: "当晚你被拉进一个 7 人微信群，群名只有个句号。没人说话。", flavor: "最危险的群，往往最安静。" },
    ],
    choices: [
      { id: "M02c1", label: "点头称是，不多嘴", arch: "hedge", lean: "FV_D", side: "left" },
      { id: "M02c2", label: "顺杆爬认个门生", arch: "ally", lean: "FV_C", side: "left" },
      { id: "M02c3", label: "高调表忠心赌一把押注靠山", arch: "obey", lean: "FV_A", side: "right" },
      { id: "M02c4", label: "当场表态跟总走", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M03", cat: "职场关系", title: "午饭圈的隐形边界",
    text: "前两周你跟着大部队去食堂，第三周发现他们聊天在你走近时总会降半拍。你端着餐盘站在原地。",
    flavor: "午饭桌是最小的派系地图。",
    minors: [
      { title: "拼桌被晾在一边", text: "你坐下后，原本热络的段子突然变成了天气。有人低头扒饭。", flavor: "冷场不是没话，是不想给你听。" },
      { title: "同事的「私下说」", text: "一个和你同批的同事午休拉你到楼梯间：「有些事，别在群里问。」", flavor: "第一个拉你进暗处的人，未必是朋友。" },
      { title: "午餐话题的试探", text: "有人「随口」问你以前哪家公司、跟谁熟。你意识到这是背调式闲聊。", flavor: "随口，是最用力的打探。" },
      { title: "被邀请进小群", text: "周五有人甩你一个群二维码：「以后消息灵通点。」你扫了，没敢说话。", flavor: "进了门，才知道门后也分前后。" },
    ],
    choices: [
      { id: "M03c1", label: "假装没察觉，照常去", arch: "dodge", lean: "FV_D", side: "left" },
      { id: "M03c2", label: "带零食主动破冰", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M03c3", label: "远远观察不接话，暗记谁说了什么", arch: "hedge", lean: "FV_A", side: "right" },
      { id: "M03c4", label: "自己组个新人局", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M04", cat: "家庭", title: "家人问你进的是不是正经公司",
    text: "母亲在电话里说：「你爸老同事的儿子在国企，铁饭碗。你那公司，网上查不到几条好评。」",
    flavor: "最朴素的考核，来自没上过班的亲人。",
    minors: [
      { title: "父母的国企滤镜", text: "家里人认为「打卡下班、五险一金、领导叫同志」才是正经工作。", flavor: "他们担心的不是你累，是你不稳。" },
      { title: "亲戚的「帮忙」请求", text: "舅舅打电话来，问能不能「内部价」拿点你们的产品。你后背一凉。", flavor: "血缘是最难拒的违规邀请。" },
      { title: "相亲时的身份牌", text: "介绍人把你描述成「某大集团旗下」，你没好意思纠正那是合资壳。", flavor: "标签比真相先到。" },
      { title: "月末的账单", text: "房租水电压下来，你算了一下，这月起码不会月光了。稍微踏实。", flavor: "钱到账的那一刻，质疑会闭嘴。" },
    ],
    choices: [
      { id: "M04c1", label: "报喜不报忧", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M04c2", label: "认真解释公司前景", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M04c3", label: "半真半假留后路，防被念", arch: "self", lean: "FV_A", side: "right" },
      { id: "M04c4", label: "立上进人设换自主权", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M05", cat: "客户", title: "新人的第一个大客户",
    text: "经理把一家区域连锁甩给你跟：「练手用的，丢了也不怪你。」可你知道，这是看你能不能扛事。",
    flavor: "练手是假，试错成本是你背。",
    minors: [
      { title: "第一次拜访的迟到", text: "客户在写字楼大堂等你，你因为地铁故障晚了七分钟。对方看了眼表。", flavor: "第一印象的刻度，是分钟。" },
      { title: "客户的点单习惯", text: "对方只喝美式不加糖，却记得你上次随口说的偏好。你被反客为主。", flavor: "被记住，是被拿捏的开始。" },
      { title: "报价单的零头", text: "你在报价里留了 2% 议价空间，客户一眼看穿：「你们留了后手啊。」", flavor: "留后手被看穿，等于没留。" },
      { title: "经理的「别承诺太多」", text: "你激动地想拍胸脯，经理微信弹来：「话别说死，交付比嘴快。」", flavor: "他拦你的，是曾经的自己。" },
    ],
    choices: [
      { id: "M05c1", label: "按流程稳稳推进", arch: "dodge", lean: "FV_B", side: "left" },
      { id: "M05c2", label: "多跑两趟混脸熟", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M05c3", label: "保守承诺暗留余地", arch: "dodge", lean: "FV_A", side: "right" },
      { id: "M05c4", label: "让利抢单", arch: "invest", lean: "FV_D", side: "right" },
    ],
  },
  {
    id: "M06", cat: "审计", title: "一年一度的审计",
    text: "审计组进驻第三天，把你经手的三笔费用全标了黄。财务总监意味深长：「新人，配合就好。」",
    flavor: "审计查的不是账，是人。",
    minors: [
      { title: "那张说不清的餐票", text: "一张 480 的聚餐发票，备注栏你写了「团队建设」，审计员画了问号。", flavor: "模糊的备注，是最亮的红。" },
      { title: "前任留下的坑", text: "你接手的项目里有笔挂账，签字的是离职半年的前任。锅悬在半空。", flavor: "前任的坑，你的填。" },
      { title: "审计员的套话", text: "对方聊家常般问：「这流程，平时谁拍板？」你意识到他在画关系图。", flavor: "最无害的问题，藏着刀。" },
      { title: "总监的保人暗示", text: "总监私下说：「只要你说清楚，我替你担一句。」你听出这是交易。", flavor: "替你担，是要你还的。" },
    ],
    choices: [
      { id: "M06c1", label: "全交材料，不解释", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M06c2", label: "主动补正说明", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M06c3", label: "先认了再洗", arch: "self", lean: "FV_C", side: "right" },
      { id: "M06c4", label: "咬出前任的责任", arch: "betray", lean: "FV_A", side: "right" },
    ],
  },
  {
    id: "M07", cat: "绩效", title: "季度绩效复盘",
    text: "你的季度评分是 B+。主管说「不错」，却把 A 给了那个天天加班的同期。你盯着排名，胃有点紧。",
    flavor: "不错，是距离更好还差一档。",
    minors: [
      { title: "排名表上的那行", text: "你发现同批里只有你没被点名表扬。名单本身就是表态。", flavor: "没被念到名字，也是一种念法。" },
      { title: "主管的「下次机会」", text: "他说「下次争取 A」，可你清楚，下次的坑早被别人占好了。", flavor: "下次是永远的借条。" },
      { title: "同期的一句酸话", text: "拿 A 的同事拍你肩：「你也挺拼的，就是少了点运气。」你笑不出来。", flavor: "运气，是赢家给输家的台阶。" },
      { title: "绩效面谈的录音", text: "HR 悄悄开了录音。你每句话都开始掂量轻重。", flavor: "面谈室里，空气都会作证。" },
    ],
    choices: [
      { id: "M07c1", label: "接受结果，低调收尾", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M07c2", label: "请教主管改进点", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M07c3", label: "低调收尾暗留痕", arch: "dodge", lean: "FV_A", side: "right" },
      { id: "M07c4", label: "甩出超额数据争 A", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M08", cat: "危机", title: "项目突发危机",
    text: "上线前夜，合作方服务器崩了，连带你的 demo 一片白屏。客户明天九点要验收。群里已炸。",
    flavor: "demo 崩的那秒，没人记得你熬的夜。",
    minors: [
      { title: "凌晨三点的电话", text: "客户负责人直接打你手机：「我不管原因，早上我要看到东西。」", flavor: "客户不关心过程，只认结果。" },
      { title: "甩锅的第一枪", text: "技术负责人在群里 @ 你：「需求是你确认的，这锅你先背。」", flavor: "锅总是先飞向最容易被砸的人。" },
      { title: "临时救场的方案", text: "你想起还有个降级页面能用。可那是「不上台面」的备选。", flavor: "备胎上场时，没人夸它稳，只嫌它丑。" },
      { title: "总监的沉默", text: "你在群里等总监表态，他只回了个「处理中」的表情。", flavor: "大领导的沉默，是最响的站队。" },
    ],
    choices: [
      { id: "M08c1", label: "连夜兜底救火", arch: "hedge", lean: "FV_B", side: "left" },
      { id: "M08c2", label: "拉技术一起扛", arch: "ally", lean: "FV_D", side: "left" },
      { id: "M08c3", label: "连夜兜底暗自扛", arch: "self", lean: "FV_A", side: "right" },
      { id: "M08c4", label: "先斩后奏切降级", arch: "risk", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M09", cat: "站队", title: "办公室站队暗流",
    text: "两个总监为一件事在群里隔空过招，谁都不点名，但所有人都得选边回话。你被 @ 了。",
    flavor: "不站队，本身就是一种站队。",
    minors: [
      { title: "群里的「收到」竞赛", text: "一方的消息下面秒回一排收到，另一方冷清。你数着队列。", flavor: "收到的快慢，是忠诚的体温。" },
      { title: "中立同事的消失", text: "平时话最多的那个，这两天突然「在忙」，群里再没冒泡。", flavor: "最安全的姿态，是消失。" },
      { title: "一方的私下拉拢", text: "甲总助理找你吃饭：「总欣赏你，以后多走动。」你闻到交易味。", flavor: "欣赏是糖衣，走动是契约。" },
      { title: "乙总的冷处理", text: "乙总从不拉人，只在会上慢悠悠问：「这事，谁负责？」", flavor: "不拉你的人，可能正在记你的名。" },
    ],
    choices: [
      { id: "M09c1", label: "回复模糊的「收到」", arch: "hedge", lean: "FV_D", side: "left" },
      { id: "M09c2", label: "两边都客客气气", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M09c3", label: "明确站甲总", arch: "obey", lean: "FV_A", side: "right" },
      { id: "M09c4", label: "借题向乙总表忠", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M10", cat: "调动", title: "跨部门调动风声",
    text: "小道消息说要成立新事业部，从各部门抽人。有人抢着去，有人怕被发配。你的名字在传闻里。",
    flavor: "调动的电梯，向上还是向下全看风往哪吹。",
    minors: [
      { title: "名单前的窥探", text: "茶水间有人对着打印件拍照，你瞥见自己的名字在候补栏。", flavor: "候补，是体面的待定。" },
      { title: "现主管的挽留", text: "直属领导找你喝咖啡：「别走，下半年给你加担子。」你听过三遍了。", flavor: "挽留的甜，往往兑不了现。" },
      { title: "新部门的画饼", text: "新事业部的头找你聊愿景，白板画得很大，编制只有一个。", flavor: "饼越大，分到你嘴里的越薄。" },
      { title: "同事的暗自比较", text: "同期开始打听谁去谁留，眼神里多了点胜负欲。", flavor: "调动是面镜子，照出谁怕掉队。" },
    ],
    choices: [
      { id: "M10c1", label: "按兵不动等官宣", arch: "dodge", lean: "FV_D", side: "left" },
      { id: "M10c2", label: "找现主管表忠留任", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M10c3", label: "主动请缨去新部门", arch: "self", lean: "FV_A", side: "right" },
      { id: "M10c4", label: "放出想走的信号抬价", arch: "risk", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M11", cat: "裁员", title: "裁员风声",
    text: "HR 突然收紧请假，楼下多了一家猎头公司。老员工说：「这信号，三年前见过一次。」",
    flavor: "猎头楼下办公，是被优化的前奏。",
    minors: [
      { title: "请假被卡的那次", text: "你牙疼想请半天，被以「项目紧」驳回。上季度这从不是问题。", flavor: "卡你的不是牙，是预算。" },
      { title: "老员工的打包话", text: "一位十年老员工神秘说：「保命的办法，是让上面觉得你贵得有道理。」", flavor: "贵得有道理，比便宜更抗裁。" },
      { title: "名单的影子", text: "有人传优化先从「性价比低」的岗位开刀。你默默算了自己的产出。", flavor: "性价比，是裁员的尺。" },
      { title: "同事的简历更新", text: "你发现平时最安稳的同事，领英悄悄亮了「看机会」绿灯。", flavor: "绿灯亮起时，船还没沉。" },
    ],
    choices: [
      { id: "M11c1", label: "装不知道照常干", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M11c2", label: "多接核心活刷存在", arch: "grind", lean: "FV_B", side: "left" },
      { id: "M11c3", label: "抢亮点项目自保", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M11c4", label: "暗中联络猎头留后路", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M12", cat: "空降", title: "新老板空降",
    text: "集团派来个空降总，不带旧部，第一周就把所有人的汇报线改了。老人沉默，新人观望。",
    flavor: "空降的鞋，落下来之前最响。",
    minors: [
      { title: "第一周的「一对一」", text: "新总挨个谈话，问的不是业绩，是你「站哪边」。", flavor: "他不在乎你做啥，在乎你跟谁。" },
      { title: "旧流程的废除", text: "沿用三年的审批链被废，新规矩没人讲得清，全靠猜。", flavor: "旧规矩死得悄，新规矩活得累。" },
      { title: "老人的集体降温", text: "原班底突然不聊业务，只聊天气。你懂那是自保。", flavor: "沉默是会传染的。" },
      { title: "新总的「自己人」", text: "他很快从别处调来两个亲信，坐了最关键的位。", flavor: "空降的总，先落的是自己人。" },
    ],
    choices: [
      { id: "M12c1", label: "低调适应新规矩", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M12c2", label: "主动汇报表配合", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M12c3", label: "冲在前头当先锋", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M12c4", label: "摸底新总来路", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },

  // ============ 第二卷：2027.7–2028.6 站稳与暗战 ============
  {
    id: "M13", cat: "并购", title: "公司并购传闻",
    text: "午休时财经号弹出：你们母公司拟收购对手。群里一片欢呼，只有老人知道，并购等于洗牌。",
    flavor: "并购的喜报，是优化的预告片。",
    minors: [
      { title: "欢呼里的冷眼", text: "年轻人转发喜报，角落里一个老员工把手机扣在桌上。", flavor: "懂行的人，最先沉默。" },
      { title: "对手同事的将来", text: "传闻里被并入的就是你死对头部门。有人已经开始盘资源。", flavor: "别人的灾难，是自己的机遇清单。" },
      { title: "汇报线的悬疑", text: "大家都猜新架构怎么切，谁并谁，谁管谁，没人敢写下来。", flavor: "架构图没出，人心先乱。" },
      { title: "总部的沉默", text: "管理层对传闻既不否认也不确认，只说「以官方为准」。", flavor: "不否认，就是默认。" },
    ],
    choices: [
      { id: "M13c1", label: "不当回事照常干", arch: "dodge", lean: "FV_D", side: "left" },
      { id: "M13c2", label: "安抚团队稳军心", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M13c3", label: "押注并购后红利", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M13c4", label: "提前结交对方骨干", arch: "ally", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M14", cat: "年终奖", title: "年终奖博弈",
    text: "年终评级前，主管暗示「名额有限」，让你「理解组织的难」。你算着房贷，心里有数。",
    flavor: "理解组织的难，等于接受自己的少。",
    minors: [
      { title: "评级表的倾斜", text: "你发现评 A 的几位，都是某总的人。表格会说话。", flavor: "表格最诚实，也最听话。" },
      { title: "主管的画饼电话", text: "他说「今年紧，明年宽松」，你想起去年他也这么说。", flavor: "明年的饼，今年先欠着。" },
      { title: "同事的互相试探", text: "有人装不在意奖金，转头就找财务旁敲侧击。", flavor: "说不在乎的，最在乎。" },
      { title: "签字的那支笔", text: "确认单递到你手，金额比预期少一截。签不签都是输。", flavor: "笔落下的那刻，尊严打了折。" },
    ],
    choices: [
      { id: "M14c1", label: "默默签字认了", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M14c2", label: "礼貌谈期望差距", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M14c3", label: "摆业绩硬刚要价", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M14c4", label: "放风说外面在挖", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M15", cat: "出差", title: "长期出差的通知",
    text: "你被点名去外地驻点三个月，说是重用。行李还没收拾，家里已经传来一句「又来」。",
    flavor: "重用和发配，有时候是同一张车票。",
    minors: [
      { title: "行李箱里的家", text: "你收拾时，伴侣把你常看的书塞进去，没说话。", flavor: "没说的话，比行李重。" },
      { title: "驻点同事的排外", text: "到了才发现，当地团队对「总部来的人」本能设防。", flavor: "外派的你，是客人也是间谍。" },
      { title: "酒店的长夜", text: "异地酒店睡不着的第三晚，你刷到同事在群里聚餐。", flavor: "缺席的饭局，是最远的距。" },
      { title: "报销的拉锯", text: "差旅系统卡着你的垫款，财务说「回来再报」。你先刷爆卡。", flavor: "先垫的钱，回来未必回得来。" },
    ],
    choices: [
      { id: "M15c1", label: "服从安排走人", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M15c2", label: "安抚家里再出发", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M15c3", label: "借驻点立新功", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M15c4", label: "谈条件要补贴", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M16", cat: "反腐", title: "合规与反腐风波",
    text: "监察部门突查某条业务线，群里风声鹤唳。有人连夜删聊天记录，你想起经手过一笔灰色费用。",
    flavor: "反腐的灯一亮，影子都现形。",
    minors: [
      { title: "那笔说不清的费用", text: "你曾帮经理走账一笔「咨询费」，现在它成了定时炸弹。", flavor: "帮人走的账，最后算你头上。" },
      { title: "群聊的连夜清理", text: "凌晨有人群里发「注意言辞」，随后大批撤回。你跟着慌。", flavor: "撤回不是消失，是心虚。" },
      { title: "被约谈的同事", text: "隔壁组一个老实人先被请去喝茶，回来脸色灰白。", flavor: "第一个被请的，未必是真凶。" },
      { title: "经理的封口暗示", text: "经理微信：「这事你别乱说，组织会保护该保护的人。」", flavor: "保护，是有条件的。" },
    ],
    choices: [
      { id: "M16c1", label: "装傻配合调查", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M16c2", label: "主动交代自保", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M16c3", label: "咬出经手的上游", arch: "expose", lean: "FV_C", side: "right" },
      { id: "M16c4", label: "保经理换庇护", arch: "betray", lean: "FV_A", side: "right" },
    ],
  },
  {
    id: "M17", cat: "背锅", title: "背锅与甩锅",
    text: "一个本该别人盯的环节出了岔子，会上所有人的目光先落到你身上——因为你最后经手。",
    flavor: "最后经手的人，永远是天然背锅位。",
    minors: [
      { title: "会上那道视线", text: "总监问「谁最后碰的」，全屋目光齐刷刷转向你。", flavor: "目光落点，就是锅的落点。" },
      { title: "真凶的装无辜", text: "真正漏活的人低头记笔记，仿佛事不关己。", flavor: "演得最像的，最干净。" },
      { title: "邮件里的证据", text: "你翻出三个月前的抄送记录，能证明你提醒过。不敢立刻甩。", flavor: "证据在手，也要看甩的时机。" },
      { title: "经理的「先顶一下」", text: "他说「先顶一下，组织记得你的好」。你听过这台词。", flavor: "顶一下，往往顶到底。" },
    ],
    choices: [
      { id: "M17c1", label: "先认了再慢慢洗", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M17c2", label: "当场亮证据自清", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M17c3", label: "直接甩回真凶", arch: "betray", lean: "FV_A", side: "right" },
      { id: "M17c4", label: "拖人下水一起扛", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M18", cat: "挖角", title: "竞品挖角",
    text: "猎头深夜发来消息：竞品开出翻倍薪资，只要你带客户资源过去。你盯着屏幕，心跳快了。",
    flavor: "挖角价码，是给你的忠诚标价。",
    minors: [
      { title: "那串数字", text: "对方开的薪资是你现在的一点九倍。你算了三遍。", flavor: "数字会说话，也会诱惑。" },
      { title: "带资源的暗示", text: "猎头话里有话：「你的人脉，过去就是资产。」你警觉。", flavor: "他们买的不是你，是你认识的人。" },
      { title: "现公司的挽留", text: "你透露风声后，主管慌了，许诺「下次一定提你」。", flavor: "要走的人才值钱，留下的人不值钱。" },
      { title: "竞业条款的阴影", text: "你翻出合同，竞业禁止三年，违约赔得比offer还多。", flavor: "自由的价，写在违约条款里。" },
    ],
    choices: [
      { id: "M18c1", label: "回绝专注眼前", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M18c2", label: "拿offer当加薪筹码", arch: "leak", lean: "FV_B", side: "left" },
      { id: "M18c3", label: "真跳去竞品", arch: "betray", lean: "FV_A", side: "right" },
      { id: "M18c4", label: "假装考虑套情报", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M19", cat: "团建", title: "团建修罗场",
    text: "周末团建定在郊区，说是放松，实则分组比拼。你被分进「 shadow 组」，组长是对手的人。",
    flavor: "团建的轻松，是演给领导看的。",
    minors: [
      { title: "分组的小心思", text: "分组明显按派系切，你和「自己人」被拆散。有人笑了。", flavor: "分组表，是权力地图的微缩。" },
      { title: "敬酒的顺序战", text: "晚宴上，谁先敬总、谁被跳过，暗暗较劲。你举杯的手悬着。", flavor: "杯举错，场子就凉了。" },
      { title: "游戏里的出丑", text: "你被推上去表演，镜头对着你，对手在台下笑。", flavor: "出丑是免费的投名状。" },
      { title: "返程的车聊", text: "回程车上，组长跟你聊「以后多关照」，你听出是收编。", flavor: "车里的私话，比会场真。" },
    ],
    choices: [
      { id: "M19c1", label: "敷衍参加不抢戏", arch: "dodge", lean: "FV_D", side: "left" },
      { id: "M19c2", label: "主动暖场聚人气", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M19c3", label: "比赛里出风头", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M19c4", label: "借机挖对手组员", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M20", cat: "向上管理", title: "向上管理翻车",
    text: "你在周报里把风险写得太直，主管被大领导点名。他回你一句：「以后，先过我手。」",
    flavor: "说真话的代价，是失去说真话的资格。",
    minors: [
      { title: "周报的措辞坑", text: "你写了「存在较大隐患」，他期望的是「可控、在推进」。", flavor: "同样的险，两种写法两种命。" },
      { title: "大领导的追问", text: "会上大总盯着你主管：「这谁写的？」气氛瞬间结冰。", flavor: "被点名的上司，会记住谁点的火。" },
      { title: "主管的冷脸", text: "会后他没骂你，只说「以后走流程」。你却更怕这平静。", flavor: "比起骂，冷是更远的墙。" },
      { title: "同级的旁观", text: "隔壁组同期看你一眼，那眼神像在说「你太嫩」。", flavor: "翻车现场，观众最清楚。" },
    ],
    choices: [
      { id: "M20c1", label: "认错以后谨言", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M20c2", label: "私下赔罪补关系", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M20c3", label: "坚持专业判断", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M20c4", label: "绕过主管直陈", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M21", cat: "投诉", title: "客户投诉爆雷",
    text: "一个老客户在社交平台发长文，称你们「虚假承诺」。舆情还没起势，内部已经开锅。",
    flavor: "一颗差评，能炸一锅汤。",
    minors: [
      { title: "那篇长文的措辞", text: "客户写得极细，连你当时说的原话都引用了。你脊背发凉。", flavor: "被记住的原话，是最利的刀。" },
      { title: "内部的甩锅链", text: "销售说交付没说清，交付说销售乱承诺。你在中间被夹。", flavor: "夹心层，先被挤出水。" },
      { title: "公关的捂与导", text: "公关要你别回帖，他们说「先降温」。你手痒想解释。", flavor: "最想说话时，最该闭嘴。" },
      { title: "客户的私信", text: "客户私信你：「不是针对你，是你们公司太欺负人。」", flavor: "他分得清人，公司不分。" },
    ],
    choices: [
      { id: "M21c1", label: "按口径只听不说", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M21c2", label: "私聊客户安抚", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M21c3", label: "公开回应抢主动", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M21c4", label: "甩出销售承诺证据", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M22", cat: "供应链", title: "供应链背刺",
    text: "合作三年的供应商突然断供，转头接了竞品的单。你的交付排期瞬间悬空。",
    flavor: "三年的交情，抵不过一个更高的价。",
    minors: [
      { title: "断供的那封邮件", text: "对方轻描淡写「产能调整」，你却看到他们官网挂了竞品案例。", flavor: "官网上线，就是告别信。" },
      { title: "采购的失职", text: "你查才发现，采购早收到风声却没预警，因为「不想担惊」。", flavor: "怕担惊的人，让你担了惊。" },
      { title: "竞品的截胡", text: "竞品同期官宣「全链路打通」，时间点巧得让你牙痒。", flavor: "巧合，是最温柔的阴谋。" },
      { title: "客户的追问", text: "客户问「还能按期吗」，你答「在协调」，心里没底。", flavor: "在协调，是体面的没底。" },
    ],
    choices: [
      { id: "M22c1", label: "临时找替代货源", arch: "grind", lean: "FV_B", side: "left" },
      { id: "M22c2", label: "拉采购一起扛", arch: "shield", lean: "FV_D", side: "left" },
      { id: "M22c3", label: "砸钱抢回产能", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M22c4", label: "公开点名供应商", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M23", cat: "述职", title: "述职演讲",
    text: "年中述职，你准备了三周 PPT。上台前，对手那组的数字比你漂亮一截。",
    flavor: "述职台是放大镜，好与丑都放大。",
    minors: [
      { title: "PPT 的最后一改", text: "上台前十分钟，你主管让你「把风险那页撤了」。你照做。", flavor: "撤下的不是页，是实话。" },
      { title: "对手的漂亮数", text: "对方组的增长曲线像火箭，你怀疑有水分，没证据。", flavor: "漂亮得可疑，也漂亮得管用。" },
      { title: "台下的手机屏", text: "大领导全程低头回消息，你讲得再用力，也撞不进屏幕。", flavor: "最远的观众，是低头的人。" },
      { title: "提问环节的刀", text: "有人问「你的增长可持续吗」，你答得虚，他笑了。", flavor: "一句问，戳穿半场戏。" },
    ],
    choices: [
      { id: "M23c1", label: "稳稳讲完不炫技", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M23c2", label: "用故事拉近距离", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M23c3", label: "甩硬数据压场", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M23c4", label: "暗讽对手水分", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M24", cat: "借调", title: "借调总部的机会",
    text: "总部来函，借调你去参与一个战略项目半年。明面是培养，暗面是有人想借你探口风。",
    flavor: "借调的机票，单程还是往返看人心情。",
    minors: [
      { title: "借调函的措辞", text: "公函写得体面，却没写回归后的岗位。你品出弦外音。", flavor: "没写归处的借调，是流放前奏。" },
      { title: "现部门的松手", text: "直属领导爽快放人，快得让你怀疑自己是否被嫌。", flavor: "放得越爽，越像甩包袱。" },
      { title: "总部的接风", text: "到了总部，没人带你，你像颗棋子被摆上盘。", flavor: "棋子上了盘，才知道不是执子人。" },
      { title: "信息的夹缝", text: "两边的人都找你打听对方，你成了传声筒。", flavor: "传声筒，最先被两头嫌。" },
    ],
    choices: [
      { id: "M24c1", label: "当历练低调做", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M24c2", label: "两边都不深交", arch: "hedge", lean: "FV_B", side: "left" },
      { id: "M24c3", label: "借总部刷履历", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M24c4", label: "两头传话谋利", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },

  // ============ 第三卷：2028.7–2029.6 上升与缠斗 ============
  {
    id: "M25", cat: "师徒", title: "师徒反目",
    text: "带你入行的师傅，如今成了你晋升的拦路石。他暗示你「别太急」，你却觉得他在压你。",
    flavor: "教过你走路的人，也可能绊你一跤。",
    minors: [
      { title: "师傅的「为你好」", text: "他说「再沉淀两年」，你算算，正好卡在你提拔前。", flavor: "为你好，是最软的拦。" },
      { title: "旧情的重量", text: "你想起他教你改第一份方案的夜，下不了手翻脸。", flavor: "旧情是债，也是锁。" },
      { title: "同门的站队", text: "师门里其他人开始疏远你，仿佛你背叛了门派。", flavor: "出了师门，便是异类。" },
      { title: "机会的取舍", text: "一个能独立带项目的机会来了，接了就等于脱离师门羽翼。", flavor: "独立的第一站，是告别。" },
    ],
    choices: [
      { id: "M25c1", label: "忍着维持体面", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M25c2", label: "恭顺但暗中准备", arch: "hedge", lean: "FV_B", side: "left" },
      { id: "M25c3", label: "公开接独立项目", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M25c4", label: "揭师傅的旧账", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M26", cat: "离职", title: "离职同事的遗产",
    text: "一个老同事突然离职，留下半摊没交接的活和一个你从没听过的客户群。群里有人问「人呢」。",
    flavor: "人走了，坑留着，接的是你。",
    minors: [
      { title: "没交接的烂摊", text: "他电脑已格式化，你对着一堆无主文件发呆。", flavor: "格式化的人，留下格式化的坑。" },
      { title: "客户群的问候", text: "群里客户问「周老师呢」，你只能顶上冒充。", flavor: "冒充的第一步，是改名。" },
      { title: "他临走的话", text: "他最后私信你：「那摊别碰，水太深。」你已接了。", flavor: "提醒来迟，坑已入。" },
      { title: "遗产里的资源", text: "翻出他藏的私域名单，价值不菲，却也烫手。", flavor: "遗产好看，继承要命。" },
    ],
    choices: [
      { id: "M26c1", label: "照单全收慢慢理", arch: "grind", lean: "FV_B", side: "left" },
      { id: "M26c2", label: "拉原主管分责", arch: "shield", lean: "FV_D", side: "left" },
      { id: "M26c3", label: "据为己有立新功", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M26c4", label: "挖出他藏的雷", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M27", cat: "审批", title: "审批链卡死",
    text: "一笔关键预算卡在三级审批，签到第 2 级就躺了两周。项目等钱，领导等结果，你卡在中间。",
    flavor: "审批链最长的，是没人想担责。",
    minors: [
      { title: "第 2 级的沉默", text: "那位总把流程「再看看」，你懂他是在等上面风向。", flavor: "再看看，是等别人先动。" },
      { title: "加急的碰壁", text: "你标了「特急」，对方回「急也得按规矩」。规矩成了挡箭牌。", flavor: "规矩替人挡了箭。" },
      { title: "越级的诱惑", text: "有人怂恿你直接找大总签，可那是踩线的险棋。", flavor: "越级一步，恩怨三年。" },
      { title: "项目的停摆", text: "供应商因尾款不发，进度条不动了。全员盯着你。", flavor: "停摆的项目，盯死经手人。" },
    ],
    choices: [
      { id: "M27c1", label: "耐心催办不越级", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M27c2", label: "请主管出面推", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M27c3", label: "越级找大总签", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M27c4", label: "公开晒卡点施压", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M28", cat: "数据", title: "数据口径之争",
    text: "你和另一部门对「转化率」定义不同，同一张报表两边数字差出 20%。大领导要「统一口径」。",
    flavor: "口径统一不了，因为利益先不统一。",
    minors: [
      { title: "两张表的打架", text: "你的表好看，他的表难看，谁都不肯改自己的。", flavor: "表越好看，越舍不得改。" },
      { title: "定义的拉锯", text: "「复购算不算转化」吵了三回合，没结论。", flavor: "定义之争，是地盘之争。" },
      { title: "大领导的烦", text: "他拍板「按我的口径」，可没人敢问他口径凭啥。", flavor: "拍板的口径，只对拍板人有利。" },
      { title: "同级的甩手", text: "对方私下说「你赢了表，输了人」，你品出威胁。", flavor: "赢了数，可能输了局。" },
    ],
    choices: [
      { id: "M28c1", label: "服从统一口径", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M28c2", label: "协商折中口径", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M28c3", label: "力推自己的口径", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M28c4", label: "揭对方口径猫腻", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M29", cat: "饭局", title: "饭局潜规则",
    text: "一次关键饭局，座次、点菜、敬酒都有讲究。你第一次被推去「代表部门敬酒」，手心出汗。",
    flavor: "饭桌上的规矩，比合同还多。",
    minors: [
      { title: "座次的暗语", text: "你被安排在主宾右手边——那是「自己人」的尊位，也是靶位。", flavor: "尊位近，靶心也近。" },
      { title: "点菜的分寸", text: "你点贵了被嫌铺张，点便宜了被嫌不懂事。尺度在别人嘴里。", flavor: "点菜的分寸，是做人的分寸。" },
      { title: "敬酒的词", text: "你祝酒词背了三遍，开口还是结巴，被笑了场。", flavor: "结巴的那秒，印象定了格。" },
      { title: "散场的收尾", text: "谁买单、谁送客、谁开车，都有默契。你全接了。", flavor: "接得多的人，记性好的人。" },
    ],
    choices: [
      { id: "M29c1", label: "按吩咐稳妥办", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M29c2", label: "提前请教老手", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M29c3", label: "主动张罗撑场", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M29c4", label: "借敬酒套话", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M30", cat: "举报", title: "匿名信与举报",
    text: "内部论坛出现一封匿名信，实名点名某总「利益输送」。全公司都在看，你会不会被卷进去。",
    flavor: "匿名信的火，先烧离纸最近的人。",
    minors: [
      { title: "信里点名的关联", text: "信中提及的项目，你恰好经手过一环。心提到嗓子眼。", flavor: "沾过边，就洗不净。" },
      { title: "群里的装瞎", text: "平时最活跃的群，此刻静得像没人。大家都装没看见。", flavor: "装瞎，是成年人的护身符。" },
      { title: "监察的约谈", text: "监察部门挨个谈话，问你「有没有异常」。你答得小心。", flavor: "异常二字，最能被解释。" },
      { title: "被点名的反扑", text: "那位总反手举报「造谣」，风向一夜倒转。", flavor: "被反咬的，先疼。" },
    ],
    choices: [
      { id: "M30c1", label: "装不知配合调查", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M30c2", label: "撇清自己关联", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M30c3", label: "补刀实名附议", arch: "betray", lean: "FV_A", side: "right" },
      { id: "M30c4", label: "暗递证据给监察", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M31", cat: "期权", title: "期权兑现窗口",
    text: "入职时签的期权进入首个行权窗口，可公司估值说法不一，HR 说「建议再等等」。你犹豫。",
    flavor: "期权是遥遥无期的「可能」。",
    minors: [
      { title: "估值的罗生门", text: "内部说值钱，外部说虚高。你分不清哪句是真。", flavor: "估值是一门修辞。" },
      { title: "HR 的「等等」", text: "她说「明年更划算」，你想起合同里行权期有截止。", flavor: "等等，等掉的是窗口。" },
      { title: "同事的选择", text: "同期有人果断行权套现走人，有人全留赌上市。", flavor: "行不行权，是赌不赌。" },
      { title: "个税的提醒", text: "财务提醒你行权要缴一笔税，可能比到手还多。", flavor: "税单比承诺先到。" },
    ],
    choices: [
      { id: "M31c1", label: "听HR再观望", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M31c2", label: "咨询老员工", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M31c3", label: "果断行权落袋", arch: "cashin", lean: "FV_A", side: "right" },
      { id: "M31c4", label: "押注等上市", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M32", cat: "瓶颈", title: "职业瓶颈与中年危机",
    text: "你卡在现级别三年，上面位置被占，下面新人涌。镜子里的黑眼圈，比职级更真实。",
    flavor: "卡住的年限，是会呼吸的墙。",
    minors: [
      { title: "新人的价格", text: "招聘软件上，同岗新人的要价比你当年低两成。你被比下去。", flavor: "新人更便宜，是老员工的原罪。" },
      { title: "上面的铁板", text: "你上面的位置，那人坐了六年，没有动的意思。", flavor: "不动的人，挡住动的人。" },
      { title: "体力的滑坡", text: "连熬两晚你缓了三天，二十岁时一天就回血。", flavor: "身体先老，职级后知。" },
      { title: "家人的催促", text: "伴侣说「要不换个环境」，你听懂是「你该上进了」。", flavor: "换环境的潜台词，是换不出。" },
    ],
    choices: [
      { id: "M32c1", label: "安稳熬资历", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M32c2", label: "横向拓宽人脉", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M32c3", label: "冲一把争晋升", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M32c4", label: "谋划外部机会", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M33", cat: "危机", title: "跨部门撕逼项目",
    text: "一个跨三部门的项目，权责写得很美，出事时三部门同时后撤。你被推到前台兜底。",
    flavor: "跨部门项目，赢了一起分，输了一起推。",
    minors: [
      { title: "权责书的留白", text: "你发现 RACI 矩阵里你的名字出现在每一格「执行」。", flavor: "执行二字，是万能背锅签。" },
      { title: "三方的后撤", text: "一出事，A 说归 B，B 说归 C，C 说「我只是配合」。", flavor: "配合，是最稳的甩。" },
      { title: "客户的怒火", text: "客户只认对接人，也就是你。火全喷你脸上。", flavor: "唯一露脸的，先挨打。" },
      { title: "牵头总的甩锅", text: "牵头总在会上说「具体由某某负责」，把你推到灯下。", flavor: "灯下的人，最亮也最烫。" },
    ],
    choices: [
      { id: "M33c1", label: "默默兜底救火", arch: "grind", lean: "FV_B", side: "left" },
      { id: "M33c2", label: "拉三方共担", arch: "shield", lean: "FV_D", side: "left" },
      { id: "M33c3", label: "抢功立标杆", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M33c4", label: "晒聊天记录定责", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M34", cat: "审计", title: "总部巡检",
    text: "总部飞行检查组空降，不打招呼直接调档。你负责的那块，恰好是上次整改没闭环的。",
    flavor: "整改没闭环，巡检就来收尾。",
    minors: [
      { title: "未闭环的尾巴", text: "上次审计的问题你改了七成，剩三成卡在别人手里。", flavor: "剩的三成，最要命。" },
      { title: "检查组的脸色", text: "他们翻档极慢，却每页都拍照。你手心出汗。", flavor: "拍照的手，是记仇的手。" },
      { title: "直属的甩锅", text: "主管说「这版是你定的」，你记得是他会签的。", flavor: "会签的字，也能被说成你的。" },
      { title: "整改的窗口", text: "你趁检查间隙连夜补了材料，赌他们不细看。", flavor: "补的材料，赌的是马虎。" },
    ],
    choices: [
      { id: "M34c1", label: "如实配合检查", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M34c2", label: "主动补正闭环", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M34c3", label: "强调客观困难", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M34c4", label: "指认卡点的他人", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M35", cat: "晋升", title: "晋升答辩季",
    text: "一年一度晋升答辩，名额比申请人少一半。你的材料刚交，对手已托人递了条子。",
    flavor: "答辩是台前的戏，条子是幕后的棋。",
    minors: [
      { title: "材料的厚度", text: "你堆了三十页业绩，对手只有十页，却附了三封推荐。", flavor: "推荐的分量，重于页数。" },
      { title: "条子的传闻", text: "风声说某总已内定自己人，答辩只是走流程。", flavor: "走流程的，最不必真。" },
      { title: "评委的构成", text: "你发现评委里多半与对手同派，嘴角发苦。", flavor: "评委席，是战场的预演。" },
      { title: "答辩的彩排", text: "你对着镜子练了八遍，仍怕被问「你凭什么」。", flavor: "凭什么三字，最诛心。" },
    ],
    choices: [
      { id: "M35c1", label: "老实答辩不运作", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M35c2", label: "找导师背书", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M35c3", label: "猛冲业绩压阵", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M35c4", label: "揭内定黑幕", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M36", cat: "客户", title: "大客户续约战",
    text: "你手里最大客户合约到期，竞品带着更低报价来撬。客户负责人意味深长：「给个留下理由。」",
    flavor: "续约的理由，永远比报价难给。",
    minors: [
      { title: "竞品的低价", text: "对方报价低你两成，客户把单子拍桌上比给你看。", flavor: "拍桌的单子，是压价的戏。" },
      { title: "客户的旧情", text: "他记得你救过一次火，说「感情有，但老板看数字」。", flavor: "感情抵部分，抵不全。" },
      { title: "内部的支持", text: "你申请特价，审批又卡，销售总说「再等等」。", flavor: "等到的，常是客户走。" },
      { title: "临门的饭局", text: "续约前夜客户约你单独吃，说「聊聊以后」。你摸不准话里有话。", flavor: "单独聊的，往往定生死。" },
    ],
    choices: [
      { id: "M36c1", label: "按标准稳续约", arch: "dodge", lean: "FV_B", side: "left" },
      { id: "M36c2", label: "用服务绑客户", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M36c3", label: "压价死保客户", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M36c4", label: "挖客户内部人", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },

  // ============ 第四卷：2029.7–2030.6 高位与博弈 ============
  {
    id: "M37", cat: "汇报", title: "新业务线押注",
    text: "你力主押注一条新业务线，资源要从老业务抠。老业务的负责人，正是你的对头。",
    flavor: "新业务的血，来自老业务的伤口。",
    minors: [
      { title: "预算的争夺", text: "同样一笔钱，老业务要续命，新业务要启动。你抢了。", flavor: "抢到的预算，是抢来的仇。" },
      { title: "对头的阻拦", text: "他四处说「新线必死」，还拿了份「市场分析」佐证。", flavor: "佐证是买得到的。" },
      { title: "团队的疑虑", text: "调来的新人怕新线黄了被裁员，心不齐。", flavor: "心不齐的队，走不远。" },
      { title: "早期的信号", text: "首月数据惨淡，你顶着压力没撤，赌拐点。", flavor: "拐点前，都是至暗。" },
    ],
    choices: [
      { id: "M37c1", label: "小步试错不硬刚", arch: "hedge", lean: "FV_D", side: "left" },
      { id: "M37c2", label: "争取温和资源", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M37c3", label: "大举押注新线", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M37c4", label: "挖老业务墙角", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M38", cat: "舆情", title: "舆情危机",
    text: "一条关于你们「裁员套路」的帖子上了同城热搜，评论区开始扒旧瓜。公关电话被打爆。",
    flavor: "一条热搜，能掀翻半年的口碑。",
    minors: [
      { title: "热搜的措辞", text: "标题用了「套路」二字，比事实更抓眼。你恨得牙痒。", flavor: "词比事传得远。" },
      { title: "内部的禁言", text: "公司要求全员禁言，连朋友圈都别发。你憋得慌。", flavor: "禁言令下，谣言更肥。" },
      { title: "水军的影子", text: "你怀疑有竞品在推波，却没证据，只能干瞪。", flavor: "看不见的手，最狠。" },
      { title: "客户的询问", text: "老客户发来截图：「你们还好吧？」你回得小心翼翼。", flavor: "关心的截图，也是考题。" },
    ],
    choices: [
      { id: "M38c1", label: "静默等热度过", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M38c2", label: "私聊客户稳军心", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M38c3", label: "高调回应导舆论", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M38c4", label: "反查竞品操纵", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M39", cat: "挖角", title: "核心骨干被挖",
    text: "你最得力的下属被竞品高薪挖走，临走前把客户名单同步了过去。你又痛又警。",
    flavor: "培养的人，成了别人的刀。",
    minors: [
      { title: "离职的体面", text: "他走时请你喝咖啡，说「不是针对你」，你信一半。", flavor: "不是针对，也伤你。" },
      { title: "名单的迁移", text: "你发现他走后，三个客户开始「考虑别的方案」。", flavor: "人走，单跟着走。" },
      { title: "团队的动摇", text: "剩下的人开始算「我值多少」，心思散了。", flavor: "一个人走，一群人想。" },
      { title: "竞业的无奈", text: "他签了竞业，却去了「关联公司」，法律擦边。", flavor: "擦边的，最难追。" },
    ],
    choices: [
      { id: "M39c1", label: "体面放人稳团队", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M39c2", label: "安抚剩余骨干", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M39c3", label: "加薪锁核心层", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M39c4", label: "追查名单泄露", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M40", cat: "站队", title: "派系重组",
    text: "一次高层变动后，原有派系洗牌。昨天的盟友今天各奔东西，你站的位置忽然悬空。",
    flavor: "洗牌之后，旧位都不作数。",
    minors: [
      { title: "盟友的转身", text: "你一直跟的那位总，一夜转向新核心。你被晾在旧阵营。", flavor: "转身快的人，先上岸。" },
      { title: "新核心的招手", text: "新势力派人递话：「以前的事翻篇，来看新的。」", flavor: "翻篇的邀请，是投名状。" },
      { title: "旧部的离散", text: "原班兄弟开始各找新主，群聊渐渐沉了。", flavor: "沉的群，是散的伙。" },
      { title: "中立的窗口", text: "有人劝你「先别动，看谁坐稳」，你犹豫。", flavor: "不动的窗口，也会关。" },
    ],
    choices: [
      { id: "M40c1", label: "观望等落定", arch: "hedge", lean: "FV_D", side: "left" },
      { id: "M40c2", label: "稳住旧部不散", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M40c3", label: "押注新核心", arch: "betray", lean: "FV_A", side: "right" },
      { id: "M40c4", label: "另立山头自保", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M41", cat: "出差", title: "长期外派的抉择",
    text: "海外分支要人常驻两年，升职加薪明确，但家里刚安顿好。去，还是不去？",
    flavor: "升职的价码，常常写在离家上。",
    minors: [
      { title: "家里的沉默", text: "你提了想法，伴侣半天没说话，只说「你定」。", flavor: "你定二字，最重。" },
      { title: "职场的信号", text: "不去，等于把位置让给愿意去的人。你懂。", flavor: "让出的，是别人上位。" },
      { title: "两年的账", text: "你算过，两年回来职级能跨一级，代价是孩子少陪两载。", flavor: "职级与陪伴，二选一。" },
      { title: "同级的抉择", text: "另一个候选人也在犹豫，谁先点头谁赢。", flavor: "先点头的，先上车。" },
    ],
    choices: [
      { id: "M41c1", label: "婉拒专注本地", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M41c2", label: "谈远程兼顾", arch: "hedge", lean: "FV_B", side: "left" },
      { id: "M41c3", label: "果断赴外赌晋升", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M41c4", label: "拿外派当筹码", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M42", cat: "反腐", title: "反腐深挖",
    text: "上一轮反腐没完，这一轮直插业务核心。你早年经手的一笔返利，被重新翻出。",
    flavor: "反腐的锄头，专挖旧土。",
    minors: [
      { title: "旧返利的回响", text: "三年前那笔「市场费」，如今被定性为可疑。你心跳加速。", flavor: "旧账不旧，只是未到。" },
      { title: "线人的指认", text: "有人「配合调查」时提到了你名字，你却不知是谁。", flavor: "背后指你的人，你笑着聊过天。" },
      { title: "律师的建议", text: "你悄悄咨询，对方说「说清来源，别补材料」。", flavor: "补的材料，像补的谎。" },
      { title: "家人的担忧", text: "家人从你神态里看出事，问「是不是出事了」，你摇头。", flavor: "摇头，是最软的谎。" },
    ],
    choices: [
      { id: "M42c1", label: "配合不主动说", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M42c2", label: "提前自清说明", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M42c3", label: "咬出指使的上司", arch: "betray", lean: "FV_A", side: "right" },
      { id: "M42c4", label: "反查线人动机", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M43", cat: "背锅", title: "背锅升级与替罪",
    text: "一次更大规模的事故，上面要交「责任人」。你被层层推到台前，成了最合适的替罪羊。",
    flavor: "替罪的羊，挑最温顺的牵。",
    minors: [
      { title: "层层的下推", text: "总监推经理，经理推你，你成了漏斗最底。", flavor: "漏斗底，最先满。" },
      { title: "文件的签名", text: "你找到曾提醒风险的邮件，却被说「提醒不等于负责」。", flavor: "提醒不是盾，是佐证。" },
      { title: "上面的交易", text: "有人暗示：「扛下，调你去闲职，保级别。」你懂是发配。", flavor: "闲职是体面的贬。" },
      { title: "同情的目光", text: "同事看你的眼神带怜悯，却没人站出来说公道话。", flavor: "怜悯最廉价，也最凉。" },
    ],
    choices: [
      { id: "M43c1", label: "认下保级别", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M43c2", label: "部分担责留余地", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M43c3", label: "硬刚拒绝背锅", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M43c4", label: "拉所有人下水", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M44", cat: "竞品", title: "竞品价格战",
    text: "竞品突然全线下调 15%，你们的市场份额一周掉了一截。开不打，等死；打，流血。",
    flavor: "价格战的子弹，打在利润上。",
    minors: [
      { title: "份额的跳水", text: "周报上那条曲线，比上个月矮一截。你被总监盯。", flavor: "矮的那截，是盯你的眼。" },
      { title: "内部的分歧", text: "销售要跟价保量，财务要保利润。两拨人吵。", flavor: "保量保利，难两全。" },
      { title: "客户的观望", text: "老客户开始「再比比」，续约悬了。", flavor: "再比比，就是再想想别家。" },
      { title: "对手的底牌", text: "你怀疑对方也撑不久，只是比谁先眨眼。", flavor: "先眨眼的人，输。" },
    ],
    choices: [
      { id: "M44c1", label: "守价保利润", arch: "dodge", lean: "FV_B", side: "left" },
      { id: "M44c2", label: "局部跟价稳客", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M44c3", label: "全面应战压价", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M44c4", label: "挖对手渠道反制", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M45", cat: "团建", title: "团建后的站队",
    text: "年度大团建后，酒劲未过，几个核心围着新来的副总称兄道弟。你被晾在包厢角落。",
    flavor: "酒后的亲疏，是清醒的排位。",
    minors: [
      { title: "包厢的座次", text: "你被安排在最远位，倒酒都得站起来。你笑了笑。", flavor: "最远的位，最清的眼。" },
      { title: "副总的眼神", text: "新副总扫过你，没停，转向别人敬酒。你被跳过。", flavor: "被跳过的杯，是信号。" },
      { title: "散场的同行", text: "回程有人拉你：「以后多跟副总走动。」你听出收编意。", flavor: "走动二字，是投名。" },
      { title: "次日的温差", text: "第二天群里，昨晚围副总的人集体被@干活。你不在列。", flavor: "不在列的，是局外人。" },
    ],
    choices: [
      { id: "M45c1", label: "不当回事照常", arch: "dodge", lean: "FV_D", side: "left" },
      { id: "M45c2", label: "主动靠近副总", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M45c3", label: "另寻靠山自立", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M45c4", label: "暗记谁跳得欢", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M46", cat: "向上管理", title: "向上管理进阶",
    text: "你学会在汇报里「包装风险」，主管开始放心放权。可放权越多，你背的雷也越多。",
    flavor: "放权的另一面，是替他扛雷。",
    minors: [
      { title: "包装的尺", text: "你学会把坏消息裹糖，主管吃得下，也不再细问。", flavor: "糖衣厚了，真相薄了。" },
      { title: "放权的甜", text: "他让你直接批小额度，你第一次尝到权力的味。", flavor: "批字的笔，有点烫。" },
      { title: "雷的转移", text: "他不便出面的事，慢慢都落到你头上。你成了手。", flavor: "手越多，雷越近。" },
      { title: "依赖的代价", text: "他开始离不了你，也离不了对你的「可控」。你被缚住。", flavor: "被需要，也被捆住。" },
    ],
    choices: [
      { id: "M46c1", label: "稳妥接住放权", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M46c2", label: "用成绩换信任", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M46c3", label: "借权扩自己盘", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M46c4", label: "留痕防秋后算账", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M47", cat: "客户", title: "客户流失警报",
    text: "两家核心客户同一周说「考虑换供应商」，你嗅到竞品在批量撬。根基在晃。",
    flavor: "客户成片走，是地基裂了。",
    minors: [
      { title: "巧合的时点", text: "两家同时「考虑」，时间巧得不像巧合。你警觉。", flavor: "巧合太巧，便是局。" },
      { title: "服务的欠账", text: "你复盘才发现，上半年响应慢了，积了怨。", flavor: "怨是慢刀，割得无声。" },
      { title: "竞品的组合拳", text: "对方打包「低价+专属服务」，正中客户痛点。", flavor: "组合拳，专打软处。" },
      { title: "内部的迟钝", text: "公司反应慢半拍，你救火时已被烧了一角。", flavor: "慢半拍，烧一角。" },
    ],
    choices: [
      { id: "M47c1", label: "逐家稳客户", arch: "grind", lean: "FV_B", side: "left" },
      { id: "M47c2", label: "升级服务挽留", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M47c3", label: "砸资源抢回", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M47c4", label: "挖竞品撬角人", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M48", cat: "供应链", title: "供应链重构",
    text: "为降本，公司要换掉一半供应商，你负责的新链条没经过大促验证。风险压在你肩上。",
    flavor: "降本的刀，常切在稳定上。",
    minors: [
      { title: "新链的陌生", text: "新供应商响应慢、配合生，你天天救火。", flavor: "新的链，新的雷。" },
      { title: "旧的反弹", text: "老供应商被换，放出「质量隐患」风声，搅局。", flavor: "被换的人，会放风。" },
      { title: "大促的倒计时", text: "大促临近，新链没跑过峰值，你夜不能寐。", flavor: "没跑过的峰，最怕。" },
      { title: "降本的政绩", text: "上司把降本当政绩，催你「尽快切」，你被赶鸭。", flavor: "政绩的鞭，赶着你。" },
    ],
    choices: [
      { id: "M48c1", label: "稳过渡慢切换", arch: "hedge", lean: "FV_D", side: "left" },
      { id: "M48c2", label: "双链并行保底", arch: "shield", lean: "FV_B", side: "left" },
      { id: "M48c3", label: "全切赌降本", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M48c4", label: "曝旧商猫腻", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },

  // ============ 第五卷：2030.7–2031.6 终局与落幕 ============
  {
    id: "M49", cat: "期权", title: "期权最终兑现",
    text: "公司启动并购，你的期权终于进入兑付。可方案里「现金+股票」的比例，藏着陷阱。",
    flavor: "兑现的甜，藏在细则的苦里。",
    minors: [
      { title: "方案的措辞", text: "「现金 30%+股票 70%」，你算完发现缩水近半。", flavor: "比例一字，差之千里。" },
      { title: "同期的选择", text: "有人选全现金落袋，有人赌股票涨。两派互嘲。", flavor: "选现金的稳，选股的赌。" },
      { title: "税务的算计", text: "财务提醒你不同选择税差巨大，你头大。", flavor: "税差，是隐形的刀。" },
      { title: "签字的犹豫", text: "笔悬在纸上半天，你想起五年前那张空白合同。", flavor: "笔悬的半秒，是五年。" },
    ],
    choices: [
      { id: "M49c1", label: "听方案稳妥拿", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M49c2", label: "咨询财务再定", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M49c3", label: "选全现金落袋", arch: "cashin", lean: "FV_A", side: "right" },
      { id: "M49c4", label: "押股票博翻倍", arch: "invest", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M50", cat: "瓶颈", title: "中年危机显现",
    text: "三十五岁这年，公司偏好「年轻化」，你发现重要项目开始绕过你。镜子比职级先老。",
    flavor: "年轻化三字，是老员工的墓志铭。",
    minors: [
      { title: "绕开的会", text: "几个关键会没叫你，你从同事口里才听说。", flavor: "没被叫的会，最说明问题。" },
      { title: "新人的上位", text: "一个九五后直接对接大总，你当年的路，他抄了近道。", flavor: "近道，是时代的偏宠。" },
      { title: "体面的挣扎", text: "你开始健身、学新工具，怕被说「跟不上」。", flavor: "怕跟不上的，最拼命。" },
      { title: "家庭的镜像", text: "孩子问「爸爸为什么总加班」，你答不上来。", flavor: "答不上来的，最扎心。" },
    ],
    choices: [
      { id: "M50c1", label: "体面地稳着", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M50c2", label: "带新人传经验", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M50c3", label: "抢新项目证价值", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M50c4", label: "谋划体面转身", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M51", cat: "并购", title: "并购整合阵痛",
    text: "并购完成，两套人马并一套。你原部门的定位变得尴尬，可能被「优化」也可能被「重用」。",
    flavor: "整合的剪刀，裁掉重叠的，也裁掉多余的。",
    minors: [
      { title: "重叠的岗位", text: "对方来了个同岗的人，你们成了「二选一」。", flavor: "二选一，必有一伤。" },
      { title: "新老板的眼", text: "新总逐个谈话，问「你认同合并吗」，你听出表态题。", flavor: "认同题，是忠诚题。" },
      { title: "旧部的离散", text: "原部门有人开始找下家，气氛松散。", flavor: "松散的伙，先散。" },
      { title: "重用的信号", text: "若你被点去牵头整合，便是重用；否则，便是边缘。", flavor: "牵头与否，定生死。" },
    ],
    choices: [
      { id: "M51c1", label: "表态认同等安排", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M51c2", label: "主动融对方团队", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M51c3", label: "争牵头显价值", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M51c4", label: "留痕防被裁", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M52", cat: "晋升", title: "最后一搏的晋升",
    text: "上面的坑终于空了，你与老对手同时够格。这是你五年内最近的一次，也是最后一次。",
    flavor: "最后一次的门，最窄也最亮。",
    minors: [
      { title: "坑位的空", text: "那人调走，位子虚着。全部门都盯着。", flavor: "虚的位，是诱也是战。" },
      { title: "对手的牌", text: "老对手傍上新核心，牌面比你亮。你急。", flavor: "牌亮的，先声夺人。" },
      { title: "自己的底", text: "你翻出五年业绩，厚得能立住，却少了「关系」那张。", flavor: "业绩立得住，关系托不住。" },
      { title: "决选的前夜", text: "决选前夜你没睡，把发言稿改了又改。", flavor: "改的稿，是改的命运。" },
    ],
    choices: [
      { id: "M52c1", label: "稳扎答辩", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M52c2", label: "拉关键人背书", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M52c3", label: "孤注一掷冲", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M52c4", label: "揭对手软肋", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M53", cat: "裁员", title: "裁员落地",
    text: "优化名单终于公布，你所在的序列在列。HR 约谈，给「N+1」或「活水转岗」二选一。",
    flavor: "名单落地，比风声更冷。",
    minors: [
      { title: "约谈的室", text: "HR 室的椅子比记忆里硬，她念方案像念稿。", flavor: "念稿的人，不带情。" },
      { title: "N+1 的账", text: "你算完补偿，够半年，不够安心。", flavor: "补偿是数，安心不是。" },
      { title: "活水的虚", text: "「转岗」去的是边缘岗，明眼人都懂是缓兵。", flavor: "活水是缓兵，也是流放。" },
      { title: "同事的眼", text: "你出来时，走廊里同事低头假装没看见。", flavor: "没看见，是最体的别。" },
    ],
    choices: [
      { id: "M53c1", label: "拿N+1体面走", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M53c2", label: "谈转岗留一线", arch: "hedge", lean: "FV_B", side: "left" },
      { id: "M53c3", label: "争补偿最大化", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M53c4", label: "曝程序不公", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M54", cat: "空降", title: "空降领导的清洗",
    text: "新空降的总开始「组织优化」，先是边缘化旧部，再安插自己人。你站哪边都危险。",
    flavor: "清洗的水，先淹岸边的。",
    minors: [
      { title: "边缘的信号", text: "你负责的模块被拆，权限缩水，你成了顾问。", flavor: "顾问是体面的闲。" },
      { title: "旧部的散", text: "原班兄弟有的走有的降，群聊只剩通知。", flavor: "通知的群，是散的讣。" },
      { title: "亲信的进", text: "空降总带来的人，占了要害，你被绕开。", flavor: "绕开你，是弃你。" },
      { title: "自保的难", text: "既不能跟旧部反目，又不敢拒新总，你两难。", flavor: "两难的人，最难活。" },
    ],
    choices: [
      { id: "M54c1", label: "低调熬过清洗", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M54c2", label: "向新总表配合", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M54c3", label: "抢活证明价值", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M54c4", label: "联旧部自保", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M55", cat: "离职", title: "离职前的抉择",
    text: "你决定离开，却卡在「怎么走」：体面交接，还是带资源另起炉灶？最后一个月最难。",
    flavor: "怎么走，比走不走更难。",
    minors: [
      { title: "交接的度的", text: "你犹豫该交多细，交太细怕被说早有去意。", flavor: "细的交接，是心的远。" },
      { title: "客户的挽留", text: "老客户听说你要走，私聊「带我走」。你心动。", flavor: "带我走三字，最烫。" },
      { title: "同事的探", text: "有人旁敲你「去哪家」，你笑而不答。", flavor: "不答，是留的余地。" },
      { title: "竞业的长", text: "你看竞业期，盘算新东家能不能碰老本行。", flavor: "竞业的长，是自由的短。" },
    ],
    choices: [
      { id: "M55c1", label: "体面交接干净走", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M55c2", label: "留人脉慢慢淡", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M55c3", label: "带资源创业", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M55c4", label: "撬老客户同走", arch: "betray", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M56", cat: "师徒", title: "交接与遗产",
    text: "你开始带新人，像当年师傅带你。可你发现，自己也在重复那套「为你好」的套路。",
    flavor: "带人的人，终成曾讨厌的模样。",
    minors: [
      { title: "新人的眼", text: "新人看你，像你当年看师傅，带着不信。", flavor: "不信的眼，是过去的你。" },
      { title: "套路的复述", text: "你脱口而出「再沉淀」，吓了自己一跳。", flavor: "脱口的套，是宿命。" },
      { title: "经验的传", text: "你真心教他避坑，他未必信，像当年的你。", flavor: "信不信，由他去。" },
      { title: "遗产的题", text: "你留给他什么？是坑，还是路？你第一次想。", flavor: "留路的人，自己走过坑。" },
    ],
    choices: [
      { id: "M56c1", label: "按老法带新人", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M56c2", label: "真心倾囊相授", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M56c3", label: "推新人上位", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M56c4", label: "点破套路循环", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M57", cat: "述职", title: "终局述职与交棒",
    text: "五年最后一次述职，你不再炫数据，只讲「这套班子怎么带出来的」。台下有人红了眼。",
    flavor: "最后的述职，讲的是人，不是数。",
    minors: [
      { title: "数据的轻", text: "你没堆图表，只念了几个名字。反而安静。", flavor: "不堆的数，更重。" },
      { title: "台下的红", text: "一个老部下低头抹眼，你假装没看见。", flavor: "抹眼的，是最真的评。" },
      { title: "接棒的人", text: "你点了名让年轻人接，有人意外，有人服。", flavor: "点名的人，定未来。" },
      { title: "自己的平", text: "讲完你松了口气，五年像一场长考。", flavor: "松的气，是五年的重量。" },
    ],
    choices: [
      { id: "M57c1", label: "平稳交棒收尾", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M57c2", label: "力推接班人对", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M57c3", label: "留硬核遗产", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M57c4", label: "点破派系真相", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M58", cat: "站队", title: "派系终局站队",
    text: "大老板退休前最后一战，各派押注接班人。你这枚棋，终于被摆上明面。",
    flavor: "终局的棋，最前的子最险。",
    minors: [
      { title: "明面的摆", text: "你被点名「支持某总」，第一次上桌面。", flavor: "上桌的人，最先被记。" },
      { title: "两边的压", text: "两派都找你，许一样的条件，你只能选一边。", flavor: "一样的许，不一样的坑。" },
      { title: "退路的无", text: "你发现选中一方，便再无中立可言。", flavor: "选了，便无退。" },
      { title: "老大的眼", text: "退休的老大看你，那眼神像在说「终于」。", flavor: "终于二字，是结局。" },
    ],
    choices: [
      { id: "M58c1", label: "跟大势稳跟", arch: "hedge", lean: "FV_D", side: "left" },
      { id: "M58c2", label: "站旧主报恩", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M58c3", label: "押黑马上位", arch: "betray", lean: "FV_A", side: "right" },
      { id: "M58c4", label: "搅局谋自保", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M59", cat: "绩效", title: "五年口碑盘点",
    text: "年终，HR 拉出你五年口碑曲线：业绩稳升，但「人缘」两极化。你第一次看清自己。",
    flavor: "口碑的曲线，比工资的更诚实。",
    minors: [
      { title: "曲线的形", text: "业绩线稳，人缘线像过山车。你笑了。", flavor: "过山的缘，是性格。" },
      { title: "评价的散", text: "有人写「靠谱」，有人写「难搞」。你都认。", flavor: "难搞二字，是标签。" },
      { title: "自己的照", text: "你对着评价，想起那些翻脸与护人，都值。", flavor: "值的，是走过的。" },
      { title: "未来的题", text: "HR 问「下五年想怎样」，你竟答不出。", flavor: "答不出，是新的始。" },
    ],
    choices: [
      { id: "M59c1", label: "接纳真实口碑", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M59c2", label: "修补弱关系", arch: "ally", lean: "FV_B", side: "left" },
      { id: "M59c3", label: "冲下一座峰", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M59c4", label: "重写人设", arch: "expose", lean: "FV_C", side: "right" },
    ],
  },
  {
    id: "M60", cat: "结局", title: "离职或留任的落幕",
    text: "五年到头，去留悬在眼前。留下是熟悉的缠斗，离开是未知的海。你站在六月末的窗前。",
    flavor: "窗前的那秒，比五年都长。",
    minors: [
      { title: "留的牵", text: "留下，是那些没说完的话、没带完的人。", flavor: "没带的，是最牵的。" },
      { title: "走的怯", text: "离开，是对自己还能不能重来的不确定。", flavor: "不确定，是最怯的。" },
      { title: "家人的盼", text: "家人只问「你开心吗」，你答得慢。", flavor: "开心吗，是最难的题。" },
      { title: "自己的答", text: "你终于明白，五年教会你的，不是赢，是选。", flavor: "会选，是五年给的。" },
    ],
    choices: [
      { id: "M60c1", label: "留任续写缠斗", arch: "obey", lean: "FV_D", side: "left" },
      { id: "M60c2", label: "留任但换打法", arch: "hedge", lean: "FV_B", side: "left" },
      { id: "M60c3", label: "离职闯未知", arch: "invest", lean: "FV_A", side: "right" },
      { id: "M60c4", label: "留一手谋后路", arch: "leak", lean: "FV_C", side: "right" },
    ],
  },
];

const RANDOMS = [
  { id: "R01", cat: "偶遇", title: "电梯里偶遇大老板", text: "电梯门开，大老板独自进来，只有你们两人，还有三十层的距离。", flavor: "独处的三十层，是最短的面试。",
    choices: [ { id: "R01c1", label: "点头问好不找话", arch: "obey", lean: "FV_D", side: "left" }, { id: "R01c2", label: "聊句天气破冰", arch: "ally", lean: "FV_B", side: "left" }, { id: "R01c3", label: "一句汇报亮点", arch: "invest", lean: "FV_A", side: "right" }, { id: "R01c4", label: "试探他对某项目的态", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R02", cat: "失误", title: "咖啡泼到客户文件", text: "你手一抖，半杯美式泼在客户刚签的纸面。空气凝固。", flavor: "泼出的，是镇定。",
    choices: [ { id: "R02c1", label: "连连道歉重打印", arch: "obey", lean: "FV_D", side: "left" }, { id: "R02c2", label: "幽默化解气氛", arch: "ally", lean: "FV_B", side: "left" }, { id: "R02c3", label: "主动担责赔礼", arch: "shield", lean: "FV_A", side: "right" }, { id: "R02c4", label: "暗示是同事碰的", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R03", cat: "群聊", title: "群里发错消息", text: "你把「这总监真难搞」发到了含总监的群，三秒后才发现。", flavor: "撤回键，按得越急越慢。",
    choices: [ { id: "R03c1", label: "秒撤回装没发", arch: "obey", lean: "FV_D", side: "left" }, { id: "R03c2", label: "补个表情圆场", arch: "ally", lean: "FV_B", side: "left" }, { id: "R03c3", label: "将错就错玩笑化", arch: "invest", lean: "FV_A", side: "right" }, { id: "R03c4", label: "甩锅输入法", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R04", cat: "加班", title: "突发加班通知", text: "下班前半小时，群里弹「今晚留一下，有个急活」。你刚约了人。", flavor: "急活二字，专挑下班。",
    choices: [ { id: "R04c1", label: "默默留下干活", arch: "grind", lean: "FV_D", side: "left" }, { id: "R04c2", label: "协调改约", arch: "ally", lean: "FV_B", side: "left" }, { id: "R04c3", label: "抢着揽下露脸", arch: "invest", lean: "FV_A", side: "right" }, { id: "R04c4", label: "问清谁派的活", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R05", cat: "八卦", title: "茶水间听到秘密", text: "你倒水时，两个高管压低声音聊「下季度要动谁」。你假装没听。", flavor: "假装没听，是最贵的修养。",
    choices: [ { id: "R05c1", label: "装听不见走开", arch: "obey", lean: "FV_D", side: "left" }, { id: "R05c2", label: "淡定接水离开", arch: "dodge", lean: "FV_B", side: "left" }, { id: "R05c3", label: "记下心里有数", arch: "invest", lean: "FV_A", side: "right" }, { id: "R05c4", label: "转述给信得过的人", arch: "leak", lean: "FV_C", side: "right" } ] },
  { id: "R06", cat: "送礼", title: "过节该不该送礼", text: "中秋将至，同事都在琢磨给主管备点什么。你纠结份子钱。", flavor: "礼的重量，是关系的秤。",
    choices: [ { id: "R06c1", label: "随大流凑份子", arch: "obey", lean: "FV_D", side: "left" }, { id: "R06c2", label: "亲手写张卡", arch: "ally", lean: "FV_B", side: "left" }, { id: "R06c3", label: "单独送份厚礼", arch: "invest", lean: "FV_A", side: "right" }, { id: "R06c4", label: "不送显清高", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R07", cat: "误会", title: "被误会在背后说人", text: "有人传你「在领导那说我坏话」，当事人冷脸三天。你一头雾水。", flavor: "谣言的牙，咬的不是真相。",
    choices: [ { id: "R07c1", label: "不解释等过去", arch: "obey", lean: "FV_D", side: "left" }, { id: "R07c2", label: "主动找他聊开", arch: "ally", lean: "FV_B", side: "left" }, { id: "R07c3", label: "当面硬刚对质", arch: "invest", lean: "FV_A", side: "right" }, { id: "R07c4", label: "查出谁造谣", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R08", cat: "聚餐", title: "同事聚餐的座位", text: "周末聚餐，你到得晚，只剩主位对面的空座——那是「边缘位」。", flavor: "晚到的人，坐最远的位。",
    choices: [ { id: "R08c1", label: "坐下不介意", arch: "obey", lean: "FV_D", side: "left" }, { id: "R08c2", label: "主动张罗气氛", arch: "ally", lean: "FV_B", side: "left" }, { id: "R08c3", label: "换到热闹处", arch: "invest", lean: "FV_A", side: "right" }, { id: "R08c4", label: "借故早走避局", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R09", cat: "邮件", title: "一封措辞严厉的邮件", text: "合作方发来质问邮件，抄送了你上级。语气像在兴师问罪。", flavor: "抄送，是最软的施压。",
    choices: [ { id: "R09c1", label: "先安抚再查", arch: "obey", lean: "FV_D", side: "left" }, { id: "R09c2", label: "电话沟通降温", arch: "ally", lean: "FV_B", side: "left" }, { id: "R09c3", label: "强硬回击据理", arch: "invest", lean: "FV_A", side: "right" }, { id: "R09c4", label: "甩给上级定夺", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R10", cat: "借调", title: "被临时抓去填坑", text: "别的组急缺人，主管把你「借」过去顶半天。你的活堆着没人管。", flavor: "借出去的人，自己的活自己堆。",
    choices: [ { id: "R10c1", label: "去顶了再说", arch: "obey", lean: "FV_D", side: "left" }, { id: "R10c2", label: "协调留人手", arch: "shield", lean: "FV_B", side: "left" }, { id: "R10c3", label: "趁机混脸熟", arch: "invest", lean: "FV_A", side: "right" }, { id: "R10c4", label: "问清算谁绩效", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R11", cat: "体检", title: "年度体检的箭头", text: "报告上几处箭头朝上，医生轻描淡写「注意休息」。你想起连熬的夜。", flavor: "箭头朝上，是身体的抗议。",
    choices: [ { id: "R11c1", label: "看过就放一边", arch: "obey", lean: "FV_D", side: "left" }, { id: "R11c2", label: "约个复查", arch: "ally", lean: "FV_B", side: "left" }, { id: "R11c3", label: "立flag要养生", arch: "invest", lean: "FV_A", side: "right" }, { id: "R11c4", label: "跟同事比谁更虚", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R12", cat: "报销", title: "报销被财务退回", text: "你贴了一上午的发票，财务一句「不符规定」全退。你青筋跳。", flavor: "退回的票，是白贴的功。",
    choices: [ { id: "R12c1", label: "按规矩重贴", arch: "obey", lean: "FV_D", side: "left" }, { id: "R12c2", label: "请教老手门道", arch: "ally", lean: "FV_B", side: "left" }, { id: "R12c3", label: "找主管施压批", arch: "invest", lean: "FV_A", side: "right" }, { id: "R12c4", label: "质疑规定不合理", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R13", cat: "表扬", title: "被当众点名表扬", text: "周会上大总突然表扬你「最近很拼」。你受宠若惊，也成了靶。", flavor: "被点名，是糖也是靶。",
    choices: [ { id: "R13c1", label: "谦逊说应该的", arch: "obey", lean: "FV_D", side: "left" }, { id: "R13c2", label: "谢团队带我", arch: "ally", lean: "FV_B", side: "left" }, { id: "R13c3", label: "顺势邀功要资源", arch: "invest", lean: "FV_A", side: "right" }, { id: "R13c4", label: "暗讽有人该脸红", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R14", cat: "批评", title: "被当众点名批评", text: "同样周会，你因一个疏漏被晾出来。四十双眼睛看你。", flavor: "被晾的，最记得温度。",
    choices: [ { id: "R14c1", label: "低头认了", arch: "obey", lean: "FV_D", side: "left" }, { id: "R14c2", label: "会后补正", arch: "shield", lean: "FV_B", side: "left" }, { id: "R14c3", label: "辩解客观原因", arch: "invest", lean: "FV_A", side: "right" }, { id: "R14c4", label: "暗示有人没配合", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R15", cat: "生日", title: "工位上的生日", text: "同事偷偷给你点了蛋糕，你正焦头烂额。温情来得不合时宜。", flavor: "蛋糕的甜，衬得出累。",
    choices: [ { id: "R15c1", label: "道谢继续干", arch: "obey", lean: "FV_D", side: "left" }, { id: "R15c2", label: "停下切蛋糕", arch: "ally", lean: "FV_B", side: "left" }, { id: "R15c3", label: "请大家一起嗨", arch: "invest", lean: "FV_A", side: "right" }, { id: "R15c4", label: "记谁没来", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R16", cat: "失误", title: "PPT 放错版本", text: "汇报到一半，你发现投屏是旧版，关键数字对不上。冷汗下来。", flavor: "投屏的旧，是脸的新绿。",
    choices: [ { id: "R16c1", label: "将错就错讲完", arch: "obey", lean: "FV_D", side: "left" }, { id: "R16c2", label: "自然切新版", arch: "dodge", lean: "FV_B", side: "left" }, { id: "R16c3", label: "坦白重讲亮点", arch: "invest", lean: "FV_A", side: "right" }, { id: "R16c4", label: "赖同事没更新", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R17", cat: "竞品", title: "竞品的新海报", text: "地铁里竞品海报换了新的，slogan 直戳你们软肋。你拍了照。", flavor: "对手的标语，是你们的伤。",
    choices: [ { id: "R17c1", label: "当没看见", arch: "obey", lean: "FV_D", side: "left" }, { id: "R17c2", label: "内部提醒跟进", arch: "ally", lean: "FV_B", side: "left" }, { id: "R17c3", label: "出对标反击", arch: "invest", lean: "FV_A", side: "right" }, { id: "R17c4", label: "挖对方创意人", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R18", cat: "家庭", title: "家人突发有事", text: "上班时家里来电，老人不舒服。你盯着会议日程，进退两难。", flavor: "家与会的天平，总向你。",
    choices: [ { id: "R18c1", label: "硬撑开完会", arch: "obey", lean: "FV_D", side: "left" }, { id: "R18c2", label: "请假赶回去", arch: "ally", lean: "FV_B", side: "left" }, { id: "R18c3", label: "远程兼顾两边", arch: "invest", lean: "FV_A", side: "right" }, { id: "R18c4", label: "让伴侣全扛", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R19", cat: "培训", title: "一场可有可无的培训", text: "下午被拉去听「高效能」讲座，台上热血，台下刷手机。", flavor: "讲座的热，暖不热你。",
    choices: [ { id: "R19c1", label: "安静坐完", arch: "obey", lean: "FV_D", side: "left" }, { id: "R19c2", label: "认真记两笔", arch: "ally", lean: "FV_B", side: "left" }, { id: "R19c3", label: "提问抢镜", arch: "invest", lean: "FV_A", side: "right" }, { id: "R19c4", label: "拆台式追问", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R20", cat: "饭局", title: "临时被拉去陪客户", text: "销售喊你「过来撑个场」，你没准备，饭局却要你主谈。", flavor: "没准备的场，最考人。",
    choices: [ { id: "R20c1", label: "老实当陪衬", arch: "obey", lean: "FV_D", side: "left" }, { id: "R20c2", label: "配合销售节奏", arch: "ally", lean: "FV_B", side: "left" }, { id: "R20c3", label: "主动挑大梁", arch: "invest", lean: "FV_A", side: "right" }, { id: "R20c4", label: "摸清客户底", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R21", cat: "投票", title: "群里的一个投票", text: "行政发起「团建去哪」投票，选项里没有你想去的。你纠结投不投。", flavor: "投票的戏，是顺大流。",
    choices: [ { id: "R21c1", label: "随大流投", arch: "obey", lean: "FV_D", side: "left" }, { id: "R21c2", label: "提议新选项", arch: "ally", lean: "FV_B", side: "left" }, { id: "R21c3", label: "拉人投冷门", arch: "invest", lean: "FV_A", side: "right" }, { id: "R21c4", label: "不投显独立", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R22", cat: "对账", title: "一笔对不上的账", text: "月底对账，发现差了三百块，查一下午没出处。你怀疑自己。", flavor: "三百的差，是心的慌。",
    choices: [ { id: "R22c1", label: "挂账等以后", arch: "obey", lean: "FV_D", side: "left" }, { id: "R22c2", label: "重头核一遍", arch: "grind", lean: "FV_B", side: "left" }, { id: "R22c3", label: "自掏补平", arch: "invest", lean: "FV_A", side: "right" }, { id: "R22c4", label: "疑心有人动过", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R23", cat: "电梯", title: "电梯里碰到暗恋同事", text: "你心仪的同批同事走进来，电梯里只剩你们和暧昧的沉默。", flavor: "暧昧的电梯，停不下来的尴尬。",
    choices: [ { id: "R23c1", label: "礼貌点头", arch: "obey", lean: "FV_D", side: "left" }, { id: "R23c2", label: "聊句工作破冰", arch: "ally", lean: "FV_B", side: "left" }, { id: "R23c3", label: "约午饭加深", arch: "invest", lean: "FV_A", side: "right" }, { id: "R23c4", label: "装不认识避嫌", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R24", cat: "背锅", title: "别人的错算你头上", text: "一个你不经手的事出了岔，汇报时却归到你组。你愣住。", flavor: "归你的，未必是你的。",
    choices: [ { id: "R24c1", label: "先认下再查", arch: "obey", lean: "FV_D", side: "left" }, { id: "R24c2", label: "会后澄清", arch: "shield", lean: "FV_B", side: "left" }, { id: "R24c3", label: "当场甩回去", arch: "betray", lean: "FV_A", side: "right" }, { id: "R24c4", label: "记谁埋的雷", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R25", cat: "调薪", title: "隔壁同工涨了薪", text: "你发现同岗同事悄悄涨了，你没动静。公平感裂了条缝。", flavor: "裂缝的公平，最硌人。",
    choices: [ { id: "R25c1", label: "装不知道", arch: "obey", lean: "FV_D", side: "left" }, { id: "R25c2", label: "旁敲主管", arch: "ally", lean: "FV_B", side: "left" }, { id: "R25c3", label: "摆成绩要涨", arch: "invest", lean: "FV_A", side: "right" }, { id: "R25c4", label: "放风要跳", arch: "leak", lean: "FV_C", side: "right" } ] },
  { id: "R26", cat: "团建", title: "KTV 里的点歌", text: "团建 KTV，主管把话筒递你：「来一首。」你五音不全。", flavor: "话筒的重量，是情分的债。",
    choices: [ { id: "R26c1", label: "硬着头皮唱", arch: "obey", lean: "FV_D", side: "left" }, { id: "R26c2", label: "点首安全的", arch: "ally", lean: "FV_B", side: "left" }, { id: "R26c3", label: "抢麦带动全场", arch: "invest", lean: "FV_A", side: "right" }, { id: "R26c4", label: "装不会躲过", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R27", cat: "邮件", title: "收到一封匿名建议", text: "匿名信箱转来一条：「你被某人当枪使了。」你半信半疑。", flavor: "匿名的好意，最可疑。",
    choices: [ { id: "R27c1", label: "当恶作剧删", arch: "obey", lean: "FV_D", side: "left" }, { id: "R27c2", label: "留心观察", arch: "hedge", lean: "FV_B", side: "left" }, { id: "R27c3", label: "顺藤摸瓜", arch: "invest", lean: "FV_A", side: "right" }, { id: "R27c4", label: "反查谁发的", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R28", cat: "加班", title: "凌晨的最后一封邮件", text: "你23:50发出方案，对方秒回「收到，明天聊」。你反而更睡不着。", flavor: "秒回的收到，是新的不安。",
    choices: [ { id: "R28c1", label: "关机睡去", arch: "obey", lean: "FV_D", side: "left" }, { id: "R28c2", label: "备好明早说辞", arch: "ally", lean: "FV_B", side: "left" }, { id: "R28c3", label: "再改一版更狠", arch: "invest", lean: "FV_A", side: "right" }, { id: "R28c4", label: "看谁还在线", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R29", cat: "客户", title: "客户突然爽约", text: "约好的拜访，客户临时说「改天」，你已到楼下。", flavor: "改天二字，最空。",
    choices: [ { id: "R29c1", label: "客气改期", arch: "obey", lean: "FV_D", side: "left" }, { id: "R29c2", label: "顺手维护关系", arch: "ally", lean: "FV_B", side: "left" }, { id: "R29c3", label: "堵门也要谈", arch: "invest", lean: "FV_A", side: "right" }, { id: "R29c4", label: "问出真实原因", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R30", cat: "八卦", title: "听见有人在聊你", text: "你走近时，两人 abruptly 收声，回头冲你笑。你懂他们在说你。", flavor: "收声的笑，最刺。",
    choices: [ { id: "R30c1", label: "装没察觉", arch: "obey", lean: "FV_D", side: "left" }, { id: "R30c2", label: "自然插话破局", arch: "ally", lean: "FV_B", side: "left" }, { id: "R30c3", label: "半句玩笑反击", arch: "invest", lean: "FV_A", side: "right" }, { id: "R30c4", label: "记谁在嚼舌", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R31", cat: "系统", title: "系统崩了半小时", text: "午高峰系统宕机，全员干瞪眼，客服电话被打爆。你被推去顶。", flavor: "宕机的半小时，照出谁顶用。",
    choices: [ { id: "R31c1", label: "按预案等恢复", arch: "obey", lean: "FV_D", side: "left" }, { id: "R31c2", label: "安抚受影响方", arch: "shield", lean: "FV_B", side: "left" }, { id: "R31c3", label: "越级催技术", arch: "invest", lean: "FV_A", side: "right" }, { id: "R31c4", label: "记谁处置慢", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R32", cat: "表白", title: "被同事表白", text: "同批的他下班拦住你：「其实我……」你慌了，怕影响工作。", flavor: "表白的慌，是工作的忧。",
    choices: [ { id: "R32c1", label: "婉拒保持距", arch: "obey", lean: "FV_D", side: "left" }, { id: "R32c2", label: "说先做同事", arch: "ally", lean: "FV_B", side: "left" }, { id: "R32c3", label: "认真考虑", arch: "invest", lean: "FV_A", side: "right" }, { id: "R32c4", label: "装傻岔开", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R33", cat: "审批", title: "你的请假被卡", text: "你提前一周请假，直属说「看情况」，临期仍不批。你急事在身。", flavor: "看情况，是最不确定的批。",
    choices: [ { id: "R33c1", label: "忍着不去", arch: "obey", lean: "FV_D", side: "left" }, { id: "R33c2", label: "说明急事再请", arch: "ally", lean: "FV_B", side: "left" }, { id: "R33c3", label: "找大主管批", arch: "invest", lean: "FV_A", side: "right" }, { id: "R33c4", label: "质疑卡假动机", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R34", cat: "饭局", title: "领导家的私宴", text: "领导破例邀你去家中小聚，没叫别人。你揣着心思赴约。", flavor: "独邀的宴，是投名宴。",
    choices: [ { id: "R34c1", label: "客气做客", arch: "obey", lean: "FV_D", side: "left" }, { id: "R34c2", label: "带份心意", arch: "ally", lean: "FV_B", side: "left" }, { id: "R34c3", label: "借机表忠心", arch: "invest", lean: "FV_A", side: "right" }, { id: "R34c4", label: "套他底牌", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R35", cat: "失误", title: "误删了一段文档", text: "你手滑删了共享文档一章，回收站也清了。全员等着用。", flavor: "删的章节，是白的脸。",
    choices: [ { id: "R35c1", label: "默默重写", arch: "grind", lean: "FV_D", side: "left" }, { id: "R35c2", label: "喊人帮恢复", arch: "shield", lean: "FV_B", side: "left" }, { id: "R35c3", label: "通宵补回", arch: "invest", lean: "FV_A", side: "right" }, { id: "R35c4", label: "赖系统bug", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R36", cat: "竞品", title: "前同事的挖角饭", text: "离职的前同事约饭，席间猛夸新东家，话锋引你过去。", flavor: "前同事的夸，是挖的锄。",
    choices: [ { id: "R36c1", label: "客气道谢", arch: "obey", lean: "FV_D", side: "left" }, { id: "R36c2", label: "聊聊近况", arch: "ally", lean: "FV_B", side: "left" }, { id: "R36c3", label: "探新东家虚实", arch: "invest", lean: "FV_A", side: "right" }, { id: "R36c4", label: "套他来意", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R37", cat: "体检", title: "工位上的感冒传染", text: "流感病毒在楼层里转，你咳了两天还硬撑，怕被人说娇气。", flavor: "硬撑的咳，是倔的响。",
    choices: [ { id: "R37c1", label: "吃药硬扛", arch: "obey", lean: "FV_D", side: "left" }, { id: "R37c2", label: "戴罩少传染", arch: "ally", lean: "FV_B", side: "left" }, { id: "R37c3", label: "请假养两天", arch: "invest", lean: "FV_A", side: "right" }, { id: "R37c4", label: "吐槽环境差", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R38", cat: "群聊", title: "群里被@接急活", text: "下班点，群里@你：「这个你熟，帮看一眼。」活又来了。", flavor: "@的铃，是加班的钟。",
    choices: [ { id: "R38c1", label: "回个收到", arch: "obey", lean: "FV_D", side: "left" }, { id: "R38c2", label: "问清范围再动", arch: "ally", lean: "FV_B", side: "left" }, { id: "R38c3", label: "爽快接下露脸", arch: "invest", lean: "FV_A", side: "right" }, { id: "R38c4", label: "反问谁该管", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R39", cat: "表扬", title: "客户的一句好评", text: "客户在群里公开夸你「靠谱」，主管顺手转给了大总。", flavor: "客户的夸，最值钱。",
    choices: [ { id: "R39c1", label: "谦逊回礼", arch: "obey", lean: "FV_D", side: "left" }, { id: "R39c2", label: "谢客户维护", arch: "ally", lean: "FV_B", side: "left" }, { id: "R39c3", label: "借势要资源", arch: "invest", lean: "FV_A", side: "right" }, { id: "R39c4", label: "暗点谁没配合", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R40", cat: "失误", title: "说错了一句行话", text: "你在会上把术语说反，懂行的人笑了。你耳根发烫。", flavor: "说反的术语，是露的怯。",
    choices: [ { id: "R40c1", label: "带过不纠", arch: "obey", lean: "FV_D", side: "left" }, { id: "R40c2", label: "自嘲圆回", arch: "ally", lean: "FV_B", side: "left" }, { id: "R40c3", label: "用数据扳回", arch: "invest", lean: "FV_A", side: "right" }, { id: "R40c4", label: "甩锅口误", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R41", cat: "家庭", title: "孩子的家长会被占", text: "家长会与关键会议撞期，家人问「你来不来」。你卡在中间。", flavor: "撞期的会，难两全。",
    choices: [ { id: "R41c1", label: "去公司会", arch: "obey", lean: "FV_D", side: "left" }, { id: "R41c2", label: "协调挪时间", arch: "ally", lean: "FV_B", side: "left" }, { id: "R41c3", label: "远程家长会", arch: "invest", lean: "FV_A", side: "right" }, { id: "R41c4", label: "让伴侣全去", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R42", cat: "培训", title: "被点名做分享", text: "主管让你在例会分享经验，你从没讲过，台下有人翻白眼。", flavor: "分享的台，是最空的考场。",
    choices: [ { id: "R42c1", label: "照稿念完", arch: "obey", lean: "FV_D", side: "left" }, { id: "R42c2", label: "讲个实在案例", arch: "ally", lean: "FV_B", side: "left" }, { id: "R42c3", label: "讲干货镇场", arch: "invest", lean: "FV_A", side: "right" }, { id: "R42c4", label: "点名反问白眼者", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R43", cat: "报销", title: "一笔说不清的招待费", text: "你请客户吃了顿贵的，发票开了「会议费」。财务意味深长看你。", flavor: "巧开的票，最易被看。",
    choices: [ { id: "R43c1", label: "照实改类目", arch: "obey", lean: "FV_D", side: "left" }, { id: "R43c2", label: "补说明过关", arch: "shield", lean: "FV_B", side: "left" }, { id: "R43c3", label: "找主管兜", arch: "invest", lean: "FV_A", side: "right" }, { id: "R43c4", label: "暗示常这么干", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R44", cat: "偶遇", title: "走廊撞见在密谈的两人", text: "你转弯撞见两位总在低声谈事，他们瞬间散开，神色不自然。", flavor: "撞见的密，是避的你。",
    choices: [ { id: "R44c1", label: "点头快走", arch: "obey", lean: "FV_D", side: "left" }, { id: "R44c2", label: "自然打声招呼", arch: "ally", lean: "FV_B", side: "left" }, { id: "R44c3", label: "记下谁和谁", arch: "invest", lean: "FV_A", side: "right" }, { id: "R44c4", label: "事后探口风", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R45", cat: "投票", title: "评优的一票", text: "年底评优，你手里有票，两个候选都找过你。你为难。", flavor: "一票的难，是情与理。",
    choices: [ { id: "R45c1", label: "投关系近的", arch: "obey", lean: "FV_D", side: "left" }, { id: "R45c2", label: "投最该得的", arch: "ally", lean: "FV_B", side: "left" }, { id: "R45c3", label: "拿票换人情", arch: "invest", lean: "FV_A", side: "right" }, { id: "R45c4", label: "弃权显清高", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R46", cat: "客户", title: "客户送了份小礼", text: "合作方客户递来一份伴手礼，你接还是不接，左右为难。", flavor: "接的礼，是欠的情。",
    choices: [ { id: "R46c1", label: "婉拒显规矩", arch: "obey", lean: "FV_D", side: "left" }, { id: "R46c2", label: "收下回份心意", arch: "ally", lean: "FV_B", side: "left" }, { id: "R46c3", label: "收下加深绑定", arch: "invest", lean: "FV_A", side: "right" }, { id: "R46c4", label: "转手充公", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R47", cat: "系统", title: "新系统上线手生", text: "公司强推新 OA，你操作不熟，审批卡在自己这关半天。", flavor: "新系统的生，是老的慌。",
    choices: [ { id: "R47c1", label: "慢慢摸索", arch: "obey", lean: "FV_D", side: "left" }, { id: "R47c2", label: "问同事学", arch: "ally", lean: "FV_B", side: "left" }, { id: "R47c3", label: "提优化建议", arch: "invest", lean: "FV_A", side: "right" }, { id: "R47c4", label: "吐槽设计烂", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R48", cat: "八卦", title: "听说要砍掉你组", text: "小道说你们组要合并撤销，同事人心惶惶，活都不想干。", flavor: "风声的刀，先斩人心。",
    choices: [ { id: "R48c1", label: "不当回事", arch: "obey", lean: "FV_D", side: "left" }, { id: "R48c2", label: "稳住团队", arch: "shield", lean: "FV_B", side: "left" }, { id: "R48c3", label: "抢活证价值", arch: "invest", lean: "FV_A", side: "right" }, { id: "R48c4", label: "探风声来源", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R49", cat: "生日", title: "主管的生日局", text: "主管生日，组内凑份子，有人暗示「你多担点」。你掂量。", flavor: "份子的多，是地位的量。",
    choices: [ { id: "R49c1", label: "按份子出", arch: "obey", lean: "FV_D", side: "left" }, { id: "R49c2", label: "出中等体面", arch: "ally", lean: "FV_B", side: "left" }, { id: "R49c3", label: "多出表心意", arch: "invest", lean: "FV_A", side: "right" }, { id: "R49c4", label: "装漏消息少出", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R50", cat: "邮件", title: "一封来自总裁办的邮件", text: "你收到总裁办群发调研，末尾「欢迎实名反馈」。你犹豫写不写。", flavor: "实名的邀，最考验胆。",
    choices: [ { id: "R50c1", label: "当垃圾不理", arch: "obey", lean: "FV_D", side: "left" }, { id: "R50c2", label: "写点温和的", arch: "ally", lean: "FV_B", side: "left" }, { id: "R50c3", label: "实名提真问题", arch: "invest", lean: "FV_A", side: "right" }, { id: "R50c4", label: "套谁在背后推", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R51", cat: "加班", title: "周末被叫回公司", text: "周六上午，主管：「有个材料急用，你熟，来一趟。」你家在郊区。", flavor: "熟的人，最易被叫。",
    choices: [ { id: "R51c1", label: "赶回去弄", arch: "grind", lean: "FV_D", side: "left" }, { id: "R51c2", label: "远程发过去", arch: "dodge", lean: "FV_B", side: "left" }, { id: "R51c3", label: "趁机要调休", arch: "invest", lean: "FV_A", side: "right" }, { id: "R51c4", label: "问清谁都能弄", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R52", cat: "饭局", title: "客户宴上的劝酒", text: "客户频频举杯，你酒量一般，对方却说「不喝就是不给我面子」。", flavor: "不喝的面子，是最贵的拒。",
    choices: [ { id: "R52c1", label: "硬着头皮喝", arch: "obey", lean: "FV_D", side: "left" }, { id: "R52c2", label: "以茶代酒圆", arch: "ally", lean: "FV_B", side: "left" }, { id: "R52c3", label: "喝到位换单", arch: "invest", lean: "FV_A", side: "right" }, { id: "R52c4", label: "点破强劝不妥", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R53", cat: "群聊", title: "群里的新人冒泡", text: "新来的在群里连发三个表情包，气氛一度尴尬。老人没接话。", flavor: "冒泡的新人，是最易冷场的。",
    choices: [ { id: "R53c1", label: "不理会", arch: "obey", lean: "FV_D", side: "left" }, { id: "R53c2", label: "暖一句接话", arch: "ally", lean: "FV_B", side: "left" }, { id: "R53c3", label: "带他破冰", arch: "invest", lean: "FV_A", side: "right" }, { id: "R53c4", label: "暗记谁最冷", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R54", cat: "对账", title: "月底的突击盘点", text: "财务突然要全部门盘点资产，你那堆借出的设备对不上号。", flavor: "盘点的慌，是借出的乱。",
    choices: [ { id: "R54c1", label: "照实报缺口", arch: "obey", lean: "FV_D", side: "left" }, { id: "R54c2", label: "先补齐再报", arch: "shield", lean: "FV_B", side: "left" }, { id: "R54c3", label: "自掏补设备", arch: "invest", lean: "FV_A", side: "right" }, { id: "R54c4", label: "推给借用人", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R55", cat: "偶遇", title: "在楼下碰到对手部门头", text: "你电梯口撞见对头部门的负责人，他笑得意味深长：「最近挺忙？」", flavor: "意味的笑，是探的刀。",
    choices: [ { id: "R55c1", label: "客气应付", arch: "obey", lean: "FV_D", side: "left" }, { id: "R55c2", label: "闲聊两句", arch: "ally", lean: "FV_B", side: "left" }, { id: "R55c3", label: "亮进展压他", arch: "invest", lean: "FV_A", side: "right" }, { id: "R55c4", label: "套他真实动向", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R56", cat: "失误", title: "会议记错了时间", text: "你把跨部门会记成下午，到了发现人家上午开完了。你被点名。", flavor: "记错的时，是丢的脸。",
    choices: [ { id: "R56c1", label: "认错补纪要", arch: "obey", lean: "FV_D", side: "left" }, { id: "R56c2", label: "补发说明", arch: "shield", lean: "FV_B", side: "left" }, { id: "R56c3", label: "抢后续主导", arch: "invest", lean: "FV_A", side: "right" }, { id: "R56c4", label: "赖通知不清", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R57", cat: "培训", title: "外派学习的名额", text: "有个去总部培训的名额，主管问你想不想去。你纠结值不值。", flavor: "名额的值，是时间的价。",
    choices: [ { id: "R57c1", label: "听安排去", arch: "obey", lean: "FV_D", side: "left" }, { id: "R57c2", label: "问清收益", arch: "ally", lean: "FV_B", side: "left" }, { id: "R57c3", label: "争名额露野心", arch: "invest", lean: "FV_A", side: "right" }, { id: "R57c4", label: "让给同事攒情", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R58", cat: "客户", title: "老客户突然示好", text: "久未联系的老客户主动约饭，说是「想念合作」。你嗅到新机会。", flavor: "想念的背后，是需求。",
    choices: [ { id: "R58c1", label: "客气赴约", arch: "obey", lean: "FV_D", side: "left" }, { id: "R58c2", label: "叙旧稳关系", arch: "ally", lean: "FV_B", side: "left" }, { id: "R58c3", label: "趁热接新单", arch: "invest", lean: "FV_A", side: "right" }, { id: "R58c4", label: "探他真意图", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R59", cat: "系统", title: "你的账号被误操作锁了", text: "IT 误锁了你的权限，半天进不去系统，活全卡住。你干着急。", flavor: "锁的权限，是停的你。",
    choices: [ { id: "R59c1", label: "等IT解", arch: "obey", lean: "FV_D", side: "left" }, { id: "R59c2", label: "借同事账号", arch: "ally", lean: "FV_B", side: "left" }, { id: "R59c3", label: "催IT加急", arch: "invest", lean: "FV_A", side: "right" }, { id: "R59c4", label: "质疑流程乱", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R60", cat: "八卦", title: "传出你要升职", text: "风声说你进晋升短名单，同事看你的眼神都变了，有热有冷。", flavor: "风声的暖冷，是人心。",
    choices: [ { id: "R60c1", label: "不置可否", arch: "obey", lean: "FV_D", side: "left" }, { id: "R60c2", label: "低调照常", arch: "hedge", lean: "FV_B", side: "left" }, { id: "R60c3", label: "顺势攒势", arch: "invest", lean: "FV_A", side: "right" }, { id: "R60c4", label: "探谁在放风", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R61", cat: "报销", title: "差旅超标被核减", text: "你出差住了超标的酒店，报销被砍一半。你肉疼又委屈。", flavor: "砍的报销，是出的血。",
    choices: [ { id: "R61c1", label: "认了核减", arch: "obey", lean: "FV_D", side: "left" }, { id: "R61c2", label: "补说明求全", arch: "shield", lean: "FV_B", side: "left" }, { id: "R61c3", label: "找主管兜", arch: "invest", lean: "FV_A", side: "right" }, { id: "R61c4", label: "质疑标准双标", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R62", cat: "饭局", title: "和竞品的人同桌", text: "行业饭局，你发现邻座竟是竞品对口人，彼此都装着不认识。", flavor: "装不识的桌，最微妙。",
    choices: [ { id: "R62c1", label: "当陌生人不聊", arch: "obey", lean: "FV_D", side: "left" }, { id: "R62c2", label: "客气寒暄", arch: "ally", lean: "FV_B", side: "left" }, { id: "R62c3", label: "套行业风向", arch: "invest", lean: "FV_A", side: "right" }, { id: "R62c4", label: "探他底牌", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R63", cat: "群聊", title: "群里抢了红包没回", text: "主管发红包你抢了最大，却忘了说谢谢，群里静了一瞬。", flavor: "抢的红包，是忘的谢。",
    choices: [ { id: "R63c1", label: "补句谢谢", arch: "obey", lean: "FV_D", side: "left" }, { id: "R63c2", label: "发个表情圆", arch: "ally", lean: "FV_B", side: "left" }, { id: "R63c3", label: "再发个回礼", arch: "invest", lean: "FV_A", side: "right" }, { id: "R63c4", label: "装没抢到", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R64", cat: "家庭", title: "伴侣来公司送东西", text: "伴侣雨天来给你送伞，撞见你正陪客户赔笑，表情复杂。", flavor: "撞见的笑，是最酸的。",
    choices: [ { id: "R64c1", label: "匆匆接过", arch: "obey", lean: "FV_D", side: "left" }, { id: "R64c2", label: "介绍是朋友", arch: "dodge", lean: "FV_B", side: "left" }, { id: "R64c3", label: "大方介绍家人", arch: "invest", lean: "FV_A", side: "right" }, { id: "R64c4", label: "事后安抚", arch: "ally", lean: "FV_C", side: "right" } ] },
  { id: "R65", cat: "失误", title: "把报价发错客户", text: "你手误把 A 客户底价发给了 B 客户，B 立刻截图问「这价能批吗」。", flavor: "发错的价，是烫的手。",
    choices: [ { id: "R65c1", label: "圆回去说误发", arch: "obey", lean: "FV_D", side: "left" }, { id: "R65c2", label: "解释是旧版", arch: "shield", lean: "FV_B", side: "left" }, { id: "R65c3", label: "将错就错给价", arch: "invest", lean: "FV_A", side: "right" }, { id: "R65c4", label: "甩锅系统串号", arch: "betray", lean: "FV_C", side: "right" } ] },
  { id: "R66", cat: "培训", title: "被安排当小组长", text: "培训分组你被推举组长，组员却不服：「凭啥是他。」", flavor: "推的座，未必坐得稳。",
    choices: [ { id: "R66c1", label: "谦让不当", arch: "obey", lean: "FV_D", side: "left" }, { id: "R66c2", label: "服众靠做事", arch: "ally", lean: "FV_B", side: "left" }, { id: "R66c3", label: "立威带出彩", arch: "invest", lean: "FV_A", side: "right" }, { id: "R66c4", label: "点谁最刺头", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R67", cat: "对账", title: "发现一笔可疑报销", text: "你审核时看到一张陌生发票，金额不大，却像在试探底线。", flavor: "试的底线，最该堵。",
    choices: [ { id: "R67c1", label: "照过不究", arch: "obey", lean: "FV_D", side: "left" }, { id: "R67c2", label: "退回要说明", arch: "shield", lean: "FV_B", side: "left" }, { id: "R67c3", label: "上报显原则", arch: "invest", lean: "FV_A", side: "right" }, { id: "R67c4", label: "查谁在试水", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R68", cat: "偶遇", title: "在洗手间听到真话", text: "你隔间里，听见两位总抱怨「上头那决定真蠢」。你屏住呼吸。", flavor: "隔间的真，是最贵的听。",
    choices: [ { id: "R68c1", label: "悄无声息走", arch: "obey", lean: "FV_D", side: "left" }, { id: "R68c2", label: "冲水正常出", arch: "dodge", lean: "FV_B", side: "left" }, { id: "R68c3", label: "记下谁说", arch: "invest", lean: "FV_A", side: "right" }, { id: "R68c4", label: "转述可信者", arch: "leak", lean: "FV_C", side: "right" } ] },
  { id: "R69", cat: "投票", title: "团建地点的拉票", text: "有人私聊你「投海岛吧」，另有人「投温泉」。你成了被争的票。", flavor: "被争的票，是最俏的。",
    choices: [ { id: "R69c1", label: "随第一个找的", arch: "obey", lean: "FV_D", side: "left" }, { id: "R69c2", label: "按喜好投", arch: "ally", lean: "FV_B", side: "left" }, { id: "R69c3", label: "拿票换人情", arch: "invest", lean: "FV_A", side: "right" }, { id: "R69c4", label: "弃权不掺和", arch: "dodge", lean: "FV_C", side: "right" } ] },
  { id: "R70", cat: "系统", title: "新考核系统算错分", text: "系统给你的季度分明显偏低，你一核，是权重配错了。", flavor: "算错的权，是偏的心。",
    choices: [ { id: "R70c1", label: "等系统修", arch: "obey", lean: "FV_D", side: "left" }, { id: "R70c2", label: "提工单复核", arch: "shield", lean: "FV_B", side: "left" }, { id: "R70c3", label: "硬刚要重算", arch: "invest", lean: "FV_A", side: "right" }, { id: "R70c4", label: "质疑有人改权", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R71", cat: "客户", title: "客户临时改需求", text: "交付前夜，客户说「这里想换个方向」，你刚松的气又提起来。", flavor: "改的需求，是改的命。",
    choices: [ { id: "R71c1", label: "照改不抱怨", arch: "obey", lean: "FV_D", side: "left" }, { id: "R71c2", label: "谈范围保交付", arch: "ally", lean: "FV_B", side: "left" }, { id: "R71c3", label: "加人赶工接", arch: "invest", lean: "FV_A", side: "right" }, { id: "R71c4", label: "问清谁主使", arch: "expose", lean: "FV_C", side: "right" } ] },
  { id: "R72", cat: "八卦", title: "传出部门要搬址", text: "风声说整个部门要搬去远郊园区，通勤多一小时。同事都在算。", flavor: "搬的址，是远的人心。",
    choices: [ { id: "R72c1", label: "听安排不动", arch: "obey", lean: "FV_D", side: "left" }, { id: "R72c2", label: "探班车方案", arch: "ally", lean: "FV_B", side: "left" }, { id: "R72c3", label: "借机谈补贴", arch: "invest", lean: "FV_A", side: "right" }, { id: "R72c4", label: "探谁在放风", arch: "expose", lean: "FV_C", side: "right" } ] },
];

module.exports = { MAJORS, RANDOMS };
